// <auto-generated />
using System;
using HotelReserveAppServer.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReserveAppServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230927091741_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelReserveAppServer.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAmountOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 200,
                            Class = 1,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 5,
                            Number = 252
                        },
                        new
                        {
                            Id = 201,
                            Class = 1,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 6,
                            Number = 415
                        },
                        new
                        {
                            Id = 202,
                            Class = 2,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 1,
                            Number = 445
                        },
                        new
                        {
                            Id = 203,
                            Class = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 4,
                            Number = 394
                        },
                        new
                        {
                            Id = 204,
                            Class = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 5,
                            Number = 379
                        },
                        new
                        {
                            Id = 205,
                            Class = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 1,
                            Number = 337
                        },
                        new
                        {
                            Id = 206,
                            Class = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 1,
                            Number = 279
                        },
                        new
                        {
                            Id = 207,
                            Class = 2,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 4,
                            Number = 268
                        },
                        new
                        {
                            Id = 208,
                            Class = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 1,
                            Number = 307
                        },
                        new
                        {
                            Id = 209,
                            Class = 2,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 3,
                            Number = 147
                        },
                        new
                        {
                            Id = 210,
                            Class = 1,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 6,
                            Number = 285
                        },
                        new
                        {
                            Id = 211,
                            Class = 2,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 6,
                            Number = 241
                        },
                        new
                        {
                            Id = 212,
                            Class = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 5,
                            Number = 462
                        },
                        new
                        {
                            Id = 213,
                            Class = 2,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 1,
                            Number = 498
                        },
                        new
                        {
                            Id = 214,
                            Class = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 2,
                            Number = 178
                        },
                        new
                        {
                            Id = 215,
                            Class = 1,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 6,
                            Number = 395
                        },
                        new
                        {
                            Id = 216,
                            Class = 3,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 5,
                            Number = 381
                        },
                        new
                        {
                            Id = 217,
                            Class = 1,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 3,
                            Number = 466
                        },
                        new
                        {
                            Id = 218,
                            Class = 3,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 1,
                            Number = 219
                        },
                        new
                        {
                            Id = 219,
                            Class = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 4,
                            Number = 149
                        },
                        new
                        {
                            Id = 220,
                            Class = 1,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 6,
                            Number = 285
                        },
                        new
                        {
                            Id = 221,
                            Class = 1,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 1,
                            Number = 199
                        },
                        new
                        {
                            Id = 222,
                            Class = 2,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 6,
                            Number = 236
                        },
                        new
                        {
                            Id = 223,
                            Class = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 5,
                            Number = 219
                        },
                        new
                        {
                            Id = 224,
                            Class = 3,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 4,
                            Number = 504
                        },
                        new
                        {
                            Id = 225,
                            Class = 3,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 4,
                            Number = 377
                        },
                        new
                        {
                            Id = 226,
                            Class = 3,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 4,
                            Number = 345
                        },
                        new
                        {
                            Id = 227,
                            Class = 1,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 6,
                            Number = 435
                        },
                        new
                        {
                            Id = 228,
                            Class = 3,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 4,
                            Number = 176
                        },
                        new
                        {
                            Id = 229,
                            Class = 1,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 6,
                            Number = 356
                        },
                        new
                        {
                            Id = 230,
                            Class = 1,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 4,
                            Number = 326
                        },
                        new
                        {
                            Id = 231,
                            Class = 2,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 3,
                            Number = 328
                        },
                        new
                        {
                            Id = 232,
                            Class = 1,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 5,
                            Number = 460
                        },
                        new
                        {
                            Id = 233,
                            Class = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 6,
                            Number = 133
                        },
                        new
                        {
                            Id = 234,
                            Class = 2,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 6,
                            Number = 143
                        },
                        new
                        {
                            Id = 235,
                            Class = 2,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 3,
                            Number = 120
                        },
                        new
                        {
                            Id = 236,
                            Class = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 1,
                            Number = 152
                        },
                        new
                        {
                            Id = 237,
                            Class = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 5,
                            Number = 516
                        },
                        new
                        {
                            Id = 238,
                            Class = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 1,
                            Number = 278
                        },
                        new
                        {
                            Id = 239,
                            Class = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            MaxAmountOfPeople = 3,
                            Number = 156
                        },
                        new
                        {
                            Id = 240,
                            Class = 2,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 3,
                            Number = 385
                        },
                        new
                        {
                            Id = 241,
                            Class = 3,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 1,
                            Number = 288
                        },
                        new
                        {
                            Id = 242,
                            Class = 3,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 5,
                            Number = 158
                        },
                        new
                        {
                            Id = 243,
                            Class = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 5,
                            Number = 249
                        },
                        new
                        {
                            Id = 244,
                            Class = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 1,
                            Number = 252
                        },
                        new
                        {
                            Id = 245,
                            Class = 1,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 4,
                            Number = 349
                        },
                        new
                        {
                            Id = 246,
                            Class = 2,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 4,
                            Number = 395
                        },
                        new
                        {
                            Id = 247,
                            Class = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 4,
                            Number = 210
                        },
                        new
                        {
                            Id = 248,
                            Class = 2,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 3,
                            Number = 420
                        },
                        new
                        {
                            Id = 249,
                            Class = 3,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 5,
                            Number = 205
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.RoomReserve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndBookDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReserveNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartBookDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomReserves");

                    b.HasData(
                        new
                        {
                            Id = 250,
                            AdditionalInfo = "Et dolorem et molestias.",
                            EndBookDate = new DateTime(2023, 10, 5, 23, 37, 43, 104, DateTimeKind.Local).AddTicks(644),
                            ReserveNumber = 234082976,
                            RoomId = 208,
                            StartBookDate = new DateTime(2023, 9, 28, 14, 30, 57, 93, DateTimeKind.Local).AddTicks(1286),
                            UserId = new Guid("af193761-42cb-3dae-aa73-f8656822efb2")
                        },
                        new
                        {
                            Id = 251,
                            AdditionalInfo = "Assumenda et aut placeat a et qui numquam reiciendis.",
                            EndBookDate = new DateTime(2023, 10, 3, 23, 29, 47, 16, DateTimeKind.Local).AddTicks(1185),
                            ReserveNumber = 664412777,
                            RoomId = 224,
                            StartBookDate = new DateTime(2023, 9, 30, 1, 23, 51, 807, DateTimeKind.Local).AddTicks(6752),
                            UserId = new Guid("3e4ec52c-0059-f77e-8cba-60da7b02199f")
                        },
                        new
                        {
                            Id = 252,
                            AdditionalInfo = "Eos omnis optio.",
                            EndBookDate = new DateTime(2023, 10, 7, 3, 54, 52, 917, DateTimeKind.Local).AddTicks(6132),
                            ReserveNumber = 481305361,
                            RoomId = 238,
                            StartBookDate = new DateTime(2023, 10, 1, 1, 0, 14, 438, DateTimeKind.Local).AddTicks(9415),
                            UserId = new Guid("7440edd9-2cab-4358-04f8-f808f5d50fc5")
                        },
                        new
                        {
                            Id = 253,
                            AdditionalInfo = "Inventore necessitatibus doloremque quia ea.",
                            EndBookDate = new DateTime(2023, 10, 4, 9, 48, 34, 121, DateTimeKind.Local).AddTicks(6889),
                            ReserveNumber = 827411475,
                            RoomId = 238,
                            StartBookDate = new DateTime(2023, 9, 29, 9, 23, 32, 182, DateTimeKind.Local).AddTicks(4538),
                            UserId = new Guid("c7a6770d-3f78-fc23-5667-b84438d15f93")
                        },
                        new
                        {
                            Id = 254,
                            AdditionalInfo = "Deserunt laudantium temporibus molestiae sint quo est quae.",
                            EndBookDate = new DateTime(2023, 10, 6, 23, 2, 43, 254, DateTimeKind.Local).AddTicks(4286),
                            ReserveNumber = 456429641,
                            RoomId = 242,
                            StartBookDate = new DateTime(2023, 9, 30, 16, 49, 11, 488, DateTimeKind.Local).AddTicks(67),
                            UserId = new Guid("22a282cb-82b4-2fd2-66ff-eccf775cc7b0")
                        },
                        new
                        {
                            Id = 255,
                            AdditionalInfo = "Officiis error qui vitae.",
                            EndBookDate = new DateTime(2023, 10, 3, 22, 46, 20, 685, DateTimeKind.Local).AddTicks(3249),
                            ReserveNumber = 816752251,
                            RoomId = 201,
                            StartBookDate = new DateTime(2023, 9, 30, 7, 37, 54, 99, DateTimeKind.Local).AddTicks(8088),
                            UserId = new Guid("516903d2-1358-512a-96fd-4519adf6ff47")
                        },
                        new
                        {
                            Id = 256,
                            AdditionalInfo = "Ut fuga asperiores.",
                            EndBookDate = new DateTime(2023, 10, 7, 6, 49, 41, 80, DateTimeKind.Local).AddTicks(3013),
                            ReserveNumber = 220358955,
                            RoomId = 233,
                            StartBookDate = new DateTime(2023, 9, 28, 17, 22, 27, 262, DateTimeKind.Local).AddTicks(8037),
                            UserId = new Guid("4a43ad7e-7918-386e-b333-611712a9f388")
                        },
                        new
                        {
                            Id = 257,
                            AdditionalInfo = "Incidunt voluptatem tempora facere praesentium tempore at ducimus assumenda odio.",
                            EndBookDate = new DateTime(2023, 10, 5, 13, 47, 14, 704, DateTimeKind.Local).AddTicks(1669),
                            ReserveNumber = 947969518,
                            RoomId = 205,
                            StartBookDate = new DateTime(2023, 9, 29, 5, 30, 4, 27, DateTimeKind.Local).AddTicks(1964),
                            UserId = new Guid("0c18fada-9c82-9b9a-9218-6981da343366")
                        },
                        new
                        {
                            Id = 258,
                            AdditionalInfo = "At maiores cupiditate.",
                            EndBookDate = new DateTime(2023, 10, 5, 1, 51, 38, 749, DateTimeKind.Local).AddTicks(4299),
                            ReserveNumber = 175785984,
                            RoomId = 243,
                            StartBookDate = new DateTime(2023, 9, 28, 21, 46, 56, 178, DateTimeKind.Local).AddTicks(4409),
                            UserId = new Guid("df460280-dc03-cc09-e074-9c50b9834fd4")
                        },
                        new
                        {
                            Id = 259,
                            AdditionalInfo = "Sunt et ea eveniet commodi.",
                            EndBookDate = new DateTime(2023, 10, 5, 16, 33, 18, 580, DateTimeKind.Local).AddTicks(9645),
                            ReserveNumber = 770980574,
                            RoomId = 214,
                            StartBookDate = new DateTime(2023, 9, 30, 5, 44, 18, 296, DateTimeKind.Local).AddTicks(1130),
                            UserId = new Guid("7c619b4e-f8f3-2369-b8db-4752d49af18e")
                        },
                        new
                        {
                            Id = 260,
                            AdditionalInfo = "Fugit natus dicta ratione.",
                            EndBookDate = new DateTime(2023, 10, 5, 22, 49, 3, 700, DateTimeKind.Local).AddTicks(7372),
                            ReserveNumber = 636990286,
                            RoomId = 224,
                            StartBookDate = new DateTime(2023, 9, 29, 8, 11, 43, 632, DateTimeKind.Local).AddTicks(281),
                            UserId = new Guid("458205d5-2b09-1152-61ae-8f065433ac71")
                        },
                        new
                        {
                            Id = 261,
                            AdditionalInfo = "Facere dolor nihil cumque.",
                            EndBookDate = new DateTime(2023, 10, 6, 14, 58, 33, 424, DateTimeKind.Local).AddTicks(3706),
                            ReserveNumber = 191065278,
                            RoomId = 204,
                            StartBookDate = new DateTime(2023, 9, 29, 17, 11, 43, 425, DateTimeKind.Local).AddTicks(4175),
                            UserId = new Guid("7ffaf94c-6d99-4b6c-4771-4732eef20492")
                        },
                        new
                        {
                            Id = 262,
                            AdditionalInfo = "Id id fuga.",
                            EndBookDate = new DateTime(2023, 10, 5, 12, 55, 31, 260, DateTimeKind.Local).AddTicks(7598),
                            ReserveNumber = 553525333,
                            RoomId = 221,
                            StartBookDate = new DateTime(2023, 9, 29, 15, 35, 7, 454, DateTimeKind.Local).AddTicks(8829),
                            UserId = new Guid("aabb629c-5146-8109-497a-dd19239bd994")
                        },
                        new
                        {
                            Id = 263,
                            AdditionalInfo = "Nisi totam occaecati alias consequatur eius.",
                            EndBookDate = new DateTime(2023, 10, 5, 4, 58, 21, 455, DateTimeKind.Local).AddTicks(8367),
                            ReserveNumber = 168110149,
                            RoomId = 225,
                            StartBookDate = new DateTime(2023, 9, 30, 22, 0, 59, 974, DateTimeKind.Local).AddTicks(8503),
                            UserId = new Guid("1c0b5bf5-e9b0-3bf0-a193-3dcaef6c9d0f")
                        },
                        new
                        {
                            Id = 264,
                            AdditionalInfo = "Velit explicabo quam cumque possimus nihil recusandae quia.",
                            EndBookDate = new DateTime(2023, 10, 7, 5, 3, 46, 298, DateTimeKind.Local).AddTicks(9198),
                            ReserveNumber = 368919438,
                            RoomId = 238,
                            StartBookDate = new DateTime(2023, 9, 29, 11, 26, 13, 856, DateTimeKind.Local).AddTicks(3845),
                            UserId = new Guid("336e8770-4f9c-0a5d-2522-d6685e93eb7f")
                        },
                        new
                        {
                            Id = 265,
                            AdditionalInfo = "Ab id aliquam sapiente.",
                            EndBookDate = new DateTime(2023, 10, 5, 11, 59, 24, 217, DateTimeKind.Local).AddTicks(115),
                            ReserveNumber = 699086804,
                            RoomId = 218,
                            StartBookDate = new DateTime(2023, 10, 2, 5, 55, 3, 23, DateTimeKind.Local).AddTicks(3835),
                            UserId = new Guid("336e8770-4f9c-0a5d-2522-d6685e93eb7f")
                        },
                        new
                        {
                            Id = 266,
                            AdditionalInfo = "In ipsum molestiae ea sed impedit voluptas reprehenderit in voluptatem.",
                            EndBookDate = new DateTime(2023, 10, 6, 20, 8, 50, 455, DateTimeKind.Local).AddTicks(7579),
                            ReserveNumber = 495824693,
                            RoomId = 214,
                            StartBookDate = new DateTime(2023, 9, 28, 13, 16, 4, 332, DateTimeKind.Local).AddTicks(6511),
                            UserId = new Guid("b473008f-e86e-dedc-6d43-c3f7e21c62a5")
                        },
                        new
                        {
                            Id = 267,
                            AdditionalInfo = "Vitae ad voluptatum omnis consequatur vel.",
                            EndBookDate = new DateTime(2023, 10, 7, 2, 48, 41, 170, DateTimeKind.Local).AddTicks(969),
                            ReserveNumber = 342828785,
                            RoomId = 211,
                            StartBookDate = new DateTime(2023, 9, 30, 3, 16, 27, 546, DateTimeKind.Local).AddTicks(3736),
                            UserId = new Guid("b473008f-e86e-dedc-6d43-c3f7e21c62a5")
                        },
                        new
                        {
                            Id = 268,
                            AdditionalInfo = "Omnis omnis nihil laudantium assumenda quo consequatur ducimus est consequatur.",
                            EndBookDate = new DateTime(2023, 10, 7, 9, 55, 5, 696, DateTimeKind.Local).AddTicks(9968),
                            ReserveNumber = 443090176,
                            RoomId = 201,
                            StartBookDate = new DateTime(2023, 10, 1, 17, 47, 37, 95, DateTimeKind.Local).AddTicks(7400),
                            UserId = new Guid("8203e558-9069-1317-e2a9-29446961b7b8")
                        },
                        new
                        {
                            Id = 269,
                            AdditionalInfo = "Doloribus aut quo eius molestiae velit sapiente beatae aut consectetur.",
                            EndBookDate = new DateTime(2023, 10, 6, 0, 6, 5, 818, DateTimeKind.Local).AddTicks(3275),
                            ReserveNumber = 671798583,
                            RoomId = 222,
                            StartBookDate = new DateTime(2023, 9, 28, 23, 16, 43, 361, DateTimeKind.Local).AddTicks(1796),
                            UserId = new Guid("13b2b432-1bf4-f004-01c3-e1a66d98cdd9")
                        },
                        new
                        {
                            Id = 270,
                            AdditionalInfo = "Vero nesciunt neque velit ipsam eos maiores ipsa ratione.",
                            EndBookDate = new DateTime(2023, 10, 4, 23, 2, 46, 161, DateTimeKind.Local).AddTicks(8945),
                            ReserveNumber = 808993436,
                            RoomId = 207,
                            StartBookDate = new DateTime(2023, 9, 29, 8, 21, 28, 839, DateTimeKind.Local).AddTicks(640),
                            UserId = new Guid("98d02b4f-15bc-618e-afc3-d55f8d05ef56")
                        },
                        new
                        {
                            Id = 271,
                            AdditionalInfo = "Et tempore quia quia voluptas.",
                            EndBookDate = new DateTime(2023, 10, 4, 21, 18, 8, 116, DateTimeKind.Local).AddTicks(2567),
                            ReserveNumber = 679193672,
                            RoomId = 237,
                            StartBookDate = new DateTime(2023, 10, 1, 23, 4, 15, 854, DateTimeKind.Local).AddTicks(6741),
                            UserId = new Guid("c52afa4d-ebec-8a47-40da-4f4c3f336ef7")
                        },
                        new
                        {
                            Id = 272,
                            AdditionalInfo = "Voluptas quidem unde occaecati qui nostrum exercitationem.",
                            EndBookDate = new DateTime(2023, 10, 6, 2, 29, 17, 906, DateTimeKind.Local).AddTicks(3939),
                            ReserveNumber = 324168083,
                            RoomId = 224,
                            StartBookDate = new DateTime(2023, 9, 30, 19, 12, 35, 427, DateTimeKind.Local).AddTicks(4349),
                            UserId = new Guid("8140a483-abe1-45b2-8124-d25704e6c0f5")
                        },
                        new
                        {
                            Id = 273,
                            AdditionalInfo = "Sit et et reiciendis.",
                            EndBookDate = new DateTime(2023, 10, 5, 2, 59, 38, 710, DateTimeKind.Local).AddTicks(1099),
                            ReserveNumber = 390689460,
                            RoomId = 244,
                            StartBookDate = new DateTime(2023, 10, 1, 15, 52, 16, 827, DateTimeKind.Local).AddTicks(3129),
                            UserId = new Guid("f14febf6-d0f9-9575-d6df-c22de6e2dc0a")
                        },
                        new
                        {
                            Id = 274,
                            AdditionalInfo = "Inventore voluptas nihil.",
                            EndBookDate = new DateTime(2023, 10, 4, 12, 13, 24, 380, DateTimeKind.Local).AddTicks(4074),
                            ReserveNumber = 833649223,
                            RoomId = 212,
                            StartBookDate = new DateTime(2023, 10, 1, 14, 56, 22, 695, DateTimeKind.Local).AddTicks(4937),
                            UserId = new Guid("d18056c7-a888-be0c-0397-65f2661cdd64")
                        },
                        new
                        {
                            Id = 275,
                            AdditionalInfo = "Alias modi nam natus et delectus eum est quis.",
                            EndBookDate = new DateTime(2023, 10, 4, 3, 20, 46, 336, DateTimeKind.Local).AddTicks(5734),
                            ReserveNumber = 913873212,
                            RoomId = 203,
                            StartBookDate = new DateTime(2023, 9, 29, 0, 48, 8, 951, DateTimeKind.Local).AddTicks(2546),
                            UserId = new Guid("4d0dedf0-0131-69e3-6913-ea170d6a4c84")
                        },
                        new
                        {
                            Id = 276,
                            AdditionalInfo = "Saepe asperiores consequatur adipisci alias atque.",
                            EndBookDate = new DateTime(2023, 10, 6, 2, 2, 17, 299, DateTimeKind.Local).AddTicks(7270),
                            ReserveNumber = 860687362,
                            RoomId = 211,
                            StartBookDate = new DateTime(2023, 10, 1, 17, 31, 7, 21, DateTimeKind.Local).AddTicks(6832),
                            UserId = new Guid("d18056c7-a888-be0c-0397-65f2661cdd64")
                        },
                        new
                        {
                            Id = 277,
                            AdditionalInfo = "Et in cum qui tenetur cum a in.",
                            EndBookDate = new DateTime(2023, 10, 4, 11, 55, 48, 440, DateTimeKind.Local).AddTicks(8591),
                            ReserveNumber = 532405323,
                            RoomId = 215,
                            StartBookDate = new DateTime(2023, 10, 1, 4, 25, 8, 955, DateTimeKind.Local).AddTicks(7048),
                            UserId = new Guid("75234b4a-be28-4da9-dd01-6bd45a5f94f0")
                        },
                        new
                        {
                            Id = 278,
                            AdditionalInfo = "Voluptatem sint expedita.",
                            EndBookDate = new DateTime(2023, 10, 4, 6, 38, 11, 960, DateTimeKind.Local).AddTicks(7049),
                            ReserveNumber = 536008943,
                            RoomId = 240,
                            StartBookDate = new DateTime(2023, 10, 2, 1, 6, 48, 492, DateTimeKind.Local).AddTicks(2217),
                            UserId = new Guid("4a43ad7e-7918-386e-b333-611712a9f388")
                        },
                        new
                        {
                            Id = 279,
                            AdditionalInfo = "A ducimus saepe iure reiciendis.",
                            EndBookDate = new DateTime(2023, 10, 5, 10, 20, 19, 289, DateTimeKind.Local).AddTicks(8260),
                            ReserveNumber = 581212203,
                            RoomId = 215,
                            StartBookDate = new DateTime(2023, 9, 29, 7, 19, 32, 38, DateTimeKind.Local).AddTicks(5060),
                            UserId = new Guid("251196fb-f226-170a-35ee-973ca9ae84f6")
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d04d994-4eba-121d-24a5-c8407250d736"),
                            Email = "Bonita.Strosin49@hotmail.com",
                            Name = "Eladio Schumm",
                            Phone = "en",
                            UserDescription = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            Id = new Guid("4ef84899-fe9a-8416-f7c9-3d838b85bf36"),
                            Email = "Eldora.Connelly50@yahoo.com",
                            Name = "Gertrude Batz",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("c518f083-a71a-f65f-ff2d-029bde1a822a"),
                            Email = "Madge.Spinka@gmail.com",
                            Name = "Jon Fay",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("f46a7d2d-15d6-0661-b544-d56d82aac059"),
                            Email = "Lawson.Kilback@yahoo.com",
                            Name = "Brennan Larson",
                            Phone = "en",
                            UserDescription = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            Id = new Guid("c7a6770d-3f78-fc23-5667-b84438d15f93"),
                            Email = "Turner_Lesch10@yahoo.com",
                            Name = "Brian Hane",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("3e4ec52c-0059-f77e-8cba-60da7b02199f"),
                            Email = "Stuart_Medhurst69@hotmail.com",
                            Name = "Nikko Lueilwitz",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("af193761-42cb-3dae-aa73-f8656822efb2"),
                            Email = "Blake28@hotmail.com",
                            Name = "Deonte Franecki",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("a9cf9736-08cf-9c58-4f7f-585db1109667"),
                            Email = "Eriberto_Gerhold8@gmail.com",
                            Name = "Eden Feil",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("8203e558-9069-1317-e2a9-29446961b7b8"),
                            Email = "Chris58@yahoo.com",
                            Name = "Meda Schuppe",
                            Phone = "en",
                            UserDescription = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016"
                        },
                        new
                        {
                            Id = new Guid("1ab6a42a-7add-8c8d-8606-1b89e150ece4"),
                            Email = "Keegan91@yahoo.com",
                            Name = "Seth McKenzie",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("ae0ece3e-f5bc-d840-c596-65094f2b60be"),
                            Email = "Marcellus.Gerhold@yahoo.com",
                            Name = "Nestor Osinski",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("98d02b4f-15bc-618e-afc3-d55f8d05ef56"),
                            Email = "Alfreda_Lehner56@yahoo.com",
                            Name = "Watson Quigley",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("aabb629c-5146-8109-497a-dd19239bd994"),
                            Email = "Dean.Abbott@hotmail.com",
                            Name = "Deanna Zboncak",
                            Phone = "en",
                            UserDescription = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            Id = new Guid("66916fa4-6a83-b0b6-ee2c-6b69ccfe404e"),
                            Email = "Junior28@yahoo.com",
                            Name = "Angie Roob",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("909e2d48-5525-dd12-22dc-1c2b58496fe6"),
                            Email = "Megane_Becker@gmail.com",
                            Name = "Kariane Quitzon",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("9466a4a9-6b95-e46d-63c2-4ce5fba2816a"),
                            Email = "Elyssa_Cronin26@gmail.com",
                            Name = "Diego Schowalter",
                            Phone = "en",
                            UserDescription = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016"
                        },
                        new
                        {
                            Id = new Guid("458205d5-2b09-1152-61ae-8f065433ac71"),
                            Email = "Keely_Prohaska@yahoo.com",
                            Name = "Domenick Keeling",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("75234b4a-be28-4da9-dd01-6bd45a5f94f0"),
                            Email = "Pamela_Walker@gmail.com",
                            Name = "Kayli Nikolaus",
                            Phone = "en",
                            UserDescription = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            Id = new Guid("9f34e443-e219-ac06-6201-7166961931f7"),
                            Email = "Morris.Schulist61@hotmail.com",
                            Name = "Estrella Rath",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("0c18fada-9c82-9b9a-9218-6981da343366"),
                            Email = "Zachery.Rice@yahoo.com",
                            Name = "Shaina Erdman",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("d18056c7-a888-be0c-0397-65f2661cdd64"),
                            Email = "Charlene_Kihn@gmail.com",
                            Name = "Belle Kuhic",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("3b2996d9-e5b2-19d3-eb68-cd72299a8151"),
                            Email = "Vena.Smith66@hotmail.com",
                            Name = "Brock Farrell",
                            Phone = "en",
                            UserDescription = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            Id = new Guid("e2b62ef8-c6db-25d2-fddc-a215cbcca3b9"),
                            Email = "Mattie85@yahoo.com",
                            Name = "Marcelle Barrows",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("0614467b-bc02-9d42-1b39-d38ca6906c69"),
                            Email = "Henry_Ebert@gmail.com",
                            Name = "Marlin Altenwerth",
                            Phone = "en",
                            UserDescription = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            Id = new Guid("df460280-dc03-cc09-e074-9c50b9834fd4"),
                            Email = "Rhoda_Metz@gmail.com",
                            Name = "Viviane Thompson",
                            Phone = "en",
                            UserDescription = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support"
                        },
                        new
                        {
                            Id = new Guid("c52afa4d-ebec-8a47-40da-4f4c3f336ef7"),
                            Email = "Ahmad_Spinka87@gmail.com",
                            Name = "Jany Kovacek",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("11ddc22c-1778-7f8a-5aba-00ba134c765f"),
                            Email = "Maya.Zemlak3@gmail.com",
                            Name = "Rod Raynor",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("516903d2-1358-512a-96fd-4519adf6ff47"),
                            Email = "Darryl.Beatty60@gmail.com",
                            Name = "Patience Doyle",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("80e18830-7835-2577-9d08-9fa294d7e65c"),
                            Email = "Claire_Murphy@gmail.com",
                            Name = "Dominic Feeney",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("f14febf6-d0f9-9575-d6df-c22de6e2dc0a"),
                            Email = "Alda_Lind@gmail.com",
                            Name = "Deion Collins",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("12fdcb22-58df-e6dc-afec-1313c6539625"),
                            Email = "Forest76@hotmail.com",
                            Name = "Penelope Halvorson",
                            Phone = "en",
                            UserDescription = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            Id = new Guid("13b2b432-1bf4-f004-01c3-e1a66d98cdd9"),
                            Email = "Juanita.Kiehn@gmail.com",
                            Name = "Kayli Kilback",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("7440edd9-2cab-4358-04f8-f808f5d50fc5"),
                            Email = "Chance82@hotmail.com",
                            Name = "Arnold Kuvalis",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("29dce69b-f2c4-b7b9-eccc-2a3c79e1aafe"),
                            Email = "Anika.Keebler91@hotmail.com",
                            Name = "Grady Bode",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("b473008f-e86e-dedc-6d43-c3f7e21c62a5"),
                            Email = "Merlin_Fritsch@gmail.com",
                            Name = "Michele Effertz",
                            Phone = "en",
                            UserDescription = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016"
                        },
                        new
                        {
                            Id = new Guid("f65e3ac0-edba-4203-74e7-85463a60cfff"),
                            Email = "Letitia.Rodriguez@gmail.com",
                            Name = "Whitney Hudson",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("bda71648-6226-4104-8190-351763e09769"),
                            Email = "Clare82@hotmail.com",
                            Name = "Frederique Schroeder",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("a0cfb200-5e56-738a-d30e-1ee62f7d7d19"),
                            Email = "Jan11@hotmail.com",
                            Name = "Magnolia Rippin",
                            Phone = "en",
                            UserDescription = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            Id = new Guid("4a43ad7e-7918-386e-b333-611712a9f388"),
                            Email = "Magnolia55@hotmail.com",
                            Name = "Allison Brakus",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("e02c8e73-c0ab-3781-938c-0f82c2b164d5"),
                            Email = "Devonte.Weimann53@hotmail.com",
                            Name = "Eileen Mayer",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("7ffaf94c-6d99-4b6c-4771-4732eef20492"),
                            Email = "Daisy_Reynolds87@gmail.com",
                            Name = "Santiago Leannon",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("251196fb-f226-170a-35ee-973ca9ae84f6"),
                            Email = "Giovani25@gmail.com",
                            Name = "Cora Wuckert",
                            Phone = "en",
                            UserDescription = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            Id = new Guid("3906625a-7ed3-4d90-4660-a525e0a94365"),
                            Email = "Leta_Brown@hotmail.com",
                            Name = "Deshaun Huel",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("147ce235-54bb-6d99-1891-f5194310f425"),
                            Email = "Jeanie_Hahn@yahoo.com",
                            Name = "Gustave Harber",
                            Phone = "en",
                            UserDescription = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016"
                        },
                        new
                        {
                            Id = new Guid("d4d96602-ae72-c08a-b8fe-0ca24d35983d"),
                            Email = "Bridgette_Jast@hotmail.com",
                            Name = "Obie Nicolas",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("22a282cb-82b4-2fd2-66ff-eccf775cc7b0"),
                            Email = "Dan_Frami89@hotmail.com",
                            Name = "Pietro Huels",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("4d0dedf0-0131-69e3-6913-ea170d6a4c84"),
                            Email = "Mathew.Graham@hotmail.com",
                            Name = "Mozell Kris",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("8140a483-abe1-45b2-8124-d25704e6c0f5"),
                            Email = "Mozelle_Johnston@gmail.com",
                            Name = "Rasheed Littel",
                            Phone = "en",
                            UserDescription = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016"
                        },
                        new
                        {
                            Id = new Guid("7c619b4e-f8f3-2369-b8db-4752d49af18e"),
                            Email = "Jacinthe36@yahoo.com",
                            Name = "Caesar Welch",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("336e8770-4f9c-0a5d-2522-d6685e93eb7f"),
                            Email = "Andrew_Corwin@gmail.com",
                            Name = "Raphaelle Hammes",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("1c0b5bf5-e9b0-3bf0-a193-3dcaef6c9d0f"),
                            Email = "Jamison.Kutch@hotmail.com",
                            Name = "Gladys Bechtelar",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("4ac9f7f8-76e7-15c3-1731-24e7e70351db"),
                            Email = "Dawson.Larkin76@yahoo.com",
                            Name = "Vickie Rempel",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("f80c5ec4-6249-9d05-1b92-fbfc89082547"),
                            Email = "Rasheed93@gmail.com",
                            Name = "Deborah Gislason",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("2b7e20a8-e7e4-41ab-f74f-84c62ba4147a"),
                            Email = "Graciela_Mohr60@yahoo.com",
                            Name = "Katelyn Kutch",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("e4f75614-eaac-956d-03db-ddcd49a3079f"),
                            Email = "Adelia.Bogan45@yahoo.com",
                            Name = "Lindsay Raynor",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("d4c89d8e-6b6c-ac03-8399-8a0b55ced399"),
                            Email = "Derek34@gmail.com",
                            Name = "Zena Will",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("b053a2bf-c69b-efc6-1884-634d3b9b1c84"),
                            Email = "Luella19@gmail.com",
                            Name = "Shanelle Gerhold",
                            Phone = "en",
                            UserDescription = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support"
                        },
                        new
                        {
                            Id = new Guid("d6f6a459-abdc-9709-2447-271918a6a7c0"),
                            Email = "Leonardo_Williamson86@yahoo.com",
                            Name = "Irving Torp",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("0e94221c-f258-90e9-93e7-ae700d37f09f"),
                            Email = "Vivien_Hermiston@hotmail.com",
                            Name = "Sallie Reichel",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("87dbbffd-a0a3-69f0-d8e8-25429134802b"),
                            Email = "Wyman_Monahan73@yahoo.com",
                            Name = "Brigitte Torp",
                            Phone = "en",
                            UserDescription = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support"
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.RoomReserve", b =>
                {
                    b.HasOne("HotelReserveAppServer.Models.Room", "Room")
                        .WithMany("RoomReserves")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReserveAppServer.Models.User", "User")
                        .WithMany("Reserves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.Room", b =>
                {
                    b.Navigation("RoomReserves");
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.User", b =>
                {
                    b.Navigation("Reserves");
                });
#pragma warning restore 612, 618
        }
    }
}
