// <auto-generated />
using System;
using HotelReserveAppServer.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReserveAppServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230927132754_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelReserveAppServer.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAmountOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 200,
                            Class = 3,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 6,
                            Number = 365
                        },
                        new
                        {
                            Id = 201,
                            Class = 1,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 1,
                            Number = 359
                        },
                        new
                        {
                            Id = 202,
                            Class = 3,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 2,
                            Number = 220
                        },
                        new
                        {
                            Id = 203,
                            Class = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 1,
                            Number = 266
                        },
                        new
                        {
                            Id = 204,
                            Class = 2,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 5,
                            Number = 371
                        },
                        new
                        {
                            Id = 205,
                            Class = 2,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 5,
                            Number = 126
                        },
                        new
                        {
                            Id = 206,
                            Class = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 3,
                            Number = 287
                        },
                        new
                        {
                            Id = 207,
                            Class = 2,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 3,
                            Number = 390
                        },
                        new
                        {
                            Id = 208,
                            Class = 3,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 6,
                            Number = 322
                        },
                        new
                        {
                            Id = 209,
                            Class = 3,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 6,
                            Number = 284
                        },
                        new
                        {
                            Id = 210,
                            Class = 1,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 5,
                            Number = 430
                        },
                        new
                        {
                            Id = 211,
                            Class = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 3,
                            Number = 515
                        },
                        new
                        {
                            Id = 212,
                            Class = 1,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            MaxAmountOfPeople = 2,
                            Number = 410
                        },
                        new
                        {
                            Id = 213,
                            Class = 1,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 4,
                            Number = 486
                        },
                        new
                        {
                            Id = 214,
                            Class = 3,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 1,
                            Number = 457
                        },
                        new
                        {
                            Id = 215,
                            Class = 3,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 5,
                            Number = 415
                        },
                        new
                        {
                            Id = 216,
                            Class = 3,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 3,
                            Number = 163
                        },
                        new
                        {
                            Id = 217,
                            Class = 3,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 3,
                            Number = 191
                        },
                        new
                        {
                            Id = 218,
                            Class = 2,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 5,
                            Number = 184
                        },
                        new
                        {
                            Id = 219,
                            Class = 1,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 2,
                            Number = 411
                        },
                        new
                        {
                            Id = 220,
                            Class = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 5,
                            Number = 472
                        },
                        new
                        {
                            Id = 221,
                            Class = 2,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 5,
                            Number = 240
                        },
                        new
                        {
                            Id = 222,
                            Class = 3,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 1,
                            Number = 164
                        },
                        new
                        {
                            Id = 223,
                            Class = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 1,
                            Number = 153
                        },
                        new
                        {
                            Id = 224,
                            Class = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 6,
                            Number = 152
                        },
                        new
                        {
                            Id = 225,
                            Class = 3,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 1,
                            Number = 271
                        },
                        new
                        {
                            Id = 226,
                            Class = 1,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 3,
                            Number = 335
                        },
                        new
                        {
                            Id = 227,
                            Class = 3,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 4,
                            Number = 475
                        },
                        new
                        {
                            Id = 228,
                            Class = 3,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 4,
                            Number = 508
                        },
                        new
                        {
                            Id = 229,
                            Class = 3,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 1,
                            Number = 268
                        },
                        new
                        {
                            Id = 230,
                            Class = 3,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 1,
                            Number = 199
                        },
                        new
                        {
                            Id = 231,
                            Class = 3,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            MaxAmountOfPeople = 1,
                            Number = 424
                        },
                        new
                        {
                            Id = 232,
                            Class = 2,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 6,
                            Number = 107
                        },
                        new
                        {
                            Id = 233,
                            Class = 3,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 3,
                            Number = 509
                        },
                        new
                        {
                            Id = 234,
                            Class = 2,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 4,
                            Number = 164
                        },
                        new
                        {
                            Id = 235,
                            Class = 3,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 1,
                            Number = 171
                        },
                        new
                        {
                            Id = 236,
                            Class = 3,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 5,
                            Number = 452
                        },
                        new
                        {
                            Id = 237,
                            Class = 2,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 5,
                            Number = 497
                        },
                        new
                        {
                            Id = 238,
                            Class = 3,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            MaxAmountOfPeople = 3,
                            Number = 469
                        },
                        new
                        {
                            Id = 239,
                            Class = 2,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 1,
                            Number = 360
                        },
                        new
                        {
                            Id = 240,
                            Class = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 2,
                            Number = 426
                        },
                        new
                        {
                            Id = 241,
                            Class = 2,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 1,
                            Number = 503
                        },
                        new
                        {
                            Id = 242,
                            Class = 1,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 4,
                            Number = 429
                        },
                        new
                        {
                            Id = 243,
                            Class = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 2,
                            Number = 398
                        },
                        new
                        {
                            Id = 244,
                            Class = 3,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 1,
                            Number = 415
                        },
                        new
                        {
                            Id = 245,
                            Class = 3,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 6,
                            Number = 149
                        },
                        new
                        {
                            Id = 246,
                            Class = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            MaxAmountOfPeople = 1,
                            Number = 456
                        },
                        new
                        {
                            Id = 247,
                            Class = 3,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 1,
                            Number = 515
                        },
                        new
                        {
                            Id = 248,
                            Class = 3,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 2,
                            Number = 137
                        },
                        new
                        {
                            Id = 249,
                            Class = 1,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 5,
                            Number = 368
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.RoomReserve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndBookDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReserveNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartBookDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("RoomReserves");

                    b.HasData(
                        new
                        {
                            Id = 250,
                            AdditionalInfo = "Non odit libero.",
                            EndBookDate = new DateTime(2023, 10, 5, 5, 27, 10, 71, DateTimeKind.Local).AddTicks(9284),
                            ReserveNumber = 710020228,
                            RoomId = 229,
                            StartBookDate = new DateTime(2023, 9, 29, 21, 25, 21, 157, DateTimeKind.Local).AddTicks(4190),
                            UserId = new Guid("2c69cb74-3172-5b78-42b9-55dad7bdd9d3")
                        },
                        new
                        {
                            Id = 251,
                            AdditionalInfo = "Laborum quis rerum culpa sed saepe dolores iure saepe alias.",
                            EndBookDate = new DateTime(2023, 10, 6, 3, 4, 3, 579, DateTimeKind.Local).AddTicks(4597),
                            ReserveNumber = 666015383,
                            RoomId = 217,
                            StartBookDate = new DateTime(2023, 10, 1, 23, 52, 26, 281, DateTimeKind.Local).AddTicks(8246),
                            UserId = new Guid("05d6602e-2587-6aa9-984e-78f7c27f18e6")
                        },
                        new
                        {
                            Id = 252,
                            AdditionalInfo = "Consequatur porro illo.",
                            EndBookDate = new DateTime(2023, 10, 3, 18, 28, 48, 377, DateTimeKind.Local).AddTicks(3143),
                            ReserveNumber = 275963118,
                            RoomId = 226,
                            StartBookDate = new DateTime(2023, 9, 29, 5, 40, 11, 752, DateTimeKind.Local).AddTicks(924),
                            UserId = new Guid("05d6602e-2587-6aa9-984e-78f7c27f18e6")
                        },
                        new
                        {
                            Id = 253,
                            AdditionalInfo = "Sed est ab dolorum et soluta quos temporibus voluptatem.",
                            EndBookDate = new DateTime(2023, 10, 7, 14, 14, 44, 499, DateTimeKind.Local).AddTicks(2874),
                            ReserveNumber = 515996064,
                            RoomId = 235,
                            StartBookDate = new DateTime(2023, 9, 30, 5, 39, 57, 351, DateTimeKind.Local).AddTicks(2108),
                            UserId = new Guid("2a3e215c-d52b-0f32-74f0-773d3688f729")
                        },
                        new
                        {
                            Id = 254,
                            AdditionalInfo = "Laboriosam sit velit consequatur magnam rerum natus sequi consequatur et.",
                            EndBookDate = new DateTime(2023, 10, 3, 19, 49, 8, 446, DateTimeKind.Local).AddTicks(9172),
                            ReserveNumber = 453474922,
                            RoomId = 229,
                            StartBookDate = new DateTime(2023, 9, 29, 17, 43, 49, 349, DateTimeKind.Local).AddTicks(8578),
                            UserId = new Guid("6ee61463-73f9-6222-a33c-904f05f9bfb6")
                        },
                        new
                        {
                            Id = 255,
                            AdditionalInfo = "Consectetur dolorum pariatur id.",
                            EndBookDate = new DateTime(2023, 10, 4, 7, 1, 9, 987, DateTimeKind.Local).AddTicks(3979),
                            ReserveNumber = 120450893,
                            RoomId = 242,
                            StartBookDate = new DateTime(2023, 10, 2, 4, 58, 48, 277, DateTimeKind.Local).AddTicks(3732),
                            UserId = new Guid("2864e86c-7311-2523-8416-29b846f4f258")
                        },
                        new
                        {
                            Id = 256,
                            AdditionalInfo = "Ipsa accusantium dicta nesciunt aut tempore pariatur nemo.",
                            EndBookDate = new DateTime(2023, 10, 4, 7, 17, 59, 152, DateTimeKind.Local).AddTicks(6106),
                            ReserveNumber = 606429931,
                            RoomId = 226,
                            StartBookDate = new DateTime(2023, 9, 30, 4, 44, 14, 91, DateTimeKind.Local).AddTicks(7513),
                            UserId = new Guid("eb6a362a-3355-f30e-18f9-dc5d373048a6")
                        },
                        new
                        {
                            Id = 257,
                            AdditionalInfo = "Qui officiis rerum dolor alias rerum consequuntur rerum fuga.",
                            EndBookDate = new DateTime(2023, 10, 4, 3, 1, 53, 265, DateTimeKind.Local).AddTicks(4122),
                            ReserveNumber = 236698866,
                            RoomId = 220,
                            StartBookDate = new DateTime(2023, 10, 2, 7, 0, 10, 350, DateTimeKind.Local).AddTicks(2237),
                            UserId = new Guid("a9e86e7d-a75e-c926-6ba7-ff0811536b60")
                        },
                        new
                        {
                            Id = 258,
                            AdditionalInfo = "Id ab hic aut aliquid veniam rem quibusdam.",
                            EndBookDate = new DateTime(2023, 10, 5, 7, 33, 23, 847, DateTimeKind.Local).AddTicks(1482),
                            ReserveNumber = 203333518,
                            RoomId = 226,
                            StartBookDate = new DateTime(2023, 10, 1, 12, 36, 59, 776, DateTimeKind.Local).AddTicks(5966),
                            UserId = new Guid("440d27e8-af1f-eb57-892c-b7aa51baa431")
                        },
                        new
                        {
                            Id = 259,
                            AdditionalInfo = "Debitis dignissimos repudiandae cupiditate dignissimos.",
                            EndBookDate = new DateTime(2023, 10, 6, 11, 19, 37, 910, DateTimeKind.Local).AddTicks(1332),
                            ReserveNumber = 299898343,
                            RoomId = 228,
                            StartBookDate = new DateTime(2023, 9, 30, 16, 46, 54, 778, DateTimeKind.Local).AddTicks(6025),
                            UserId = new Guid("8b38ffb3-4948-249f-f254-1e0930f4dd94")
                        },
                        new
                        {
                            Id = 260,
                            AdditionalInfo = "Quam magnam voluptatem numquam et sapiente tenetur occaecati.",
                            EndBookDate = new DateTime(2023, 10, 5, 23, 48, 36, 767, DateTimeKind.Local).AddTicks(404),
                            ReserveNumber = 946509156,
                            RoomId = 200,
                            StartBookDate = new DateTime(2023, 9, 30, 3, 34, 4, 987, DateTimeKind.Local).AddTicks(2171),
                            UserId = new Guid("2c69cb74-3172-5b78-42b9-55dad7bdd9d3")
                        },
                        new
                        {
                            Id = 261,
                            AdditionalInfo = "Dolore consectetur aut molestiae natus.",
                            EndBookDate = new DateTime(2023, 10, 3, 22, 57, 9, 404, DateTimeKind.Local).AddTicks(7522),
                            ReserveNumber = 187968718,
                            RoomId = 203,
                            StartBookDate = new DateTime(2023, 9, 30, 15, 35, 49, 376, DateTimeKind.Local).AddTicks(323),
                            UserId = new Guid("a9e86e7d-a75e-c926-6ba7-ff0811536b60")
                        },
                        new
                        {
                            Id = 262,
                            AdditionalInfo = "Inventore voluptas sed alias qui perspiciatis architecto dolores.",
                            EndBookDate = new DateTime(2023, 10, 4, 3, 27, 4, 570, DateTimeKind.Local).AddTicks(9857),
                            ReserveNumber = 949679359,
                            RoomId = 226,
                            StartBookDate = new DateTime(2023, 10, 1, 14, 45, 5, 530, DateTimeKind.Local).AddTicks(981),
                            UserId = new Guid("5379cefc-3ca2-f341-03ef-99354befd137")
                        },
                        new
                        {
                            Id = 263,
                            AdditionalInfo = "Itaque accusamus et labore ut et ut non.",
                            EndBookDate = new DateTime(2023, 10, 6, 10, 39, 37, 59, DateTimeKind.Local).AddTicks(6687),
                            ReserveNumber = 425053910,
                            RoomId = 249,
                            StartBookDate = new DateTime(2023, 9, 30, 21, 19, 32, 146, DateTimeKind.Local).AddTicks(969),
                            UserId = new Guid("2a3e215c-d52b-0f32-74f0-773d3688f729")
                        },
                        new
                        {
                            Id = 264,
                            AdditionalInfo = "Autem ut possimus assumenda nemo omnis consequuntur.",
                            EndBookDate = new DateTime(2023, 10, 4, 15, 18, 50, 473, DateTimeKind.Local).AddTicks(2608),
                            ReserveNumber = 537595299,
                            RoomId = 200,
                            StartBookDate = new DateTime(2023, 9, 29, 20, 33, 17, 972, DateTimeKind.Local).AddTicks(1921),
                            UserId = new Guid("562deb07-ac26-5451-ad53-804d96ee049c")
                        },
                        new
                        {
                            Id = 265,
                            AdditionalInfo = "Consectetur id qui aperiam et iste.",
                            EndBookDate = new DateTime(2023, 10, 4, 21, 27, 53, 594, DateTimeKind.Local).AddTicks(6352),
                            ReserveNumber = 880799972,
                            RoomId = 207,
                            StartBookDate = new DateTime(2023, 10, 1, 9, 14, 55, 638, DateTimeKind.Local).AddTicks(9914),
                            UserId = new Guid("387d57a1-5db9-2c43-07d8-f5791de895ca")
                        },
                        new
                        {
                            Id = 266,
                            AdditionalInfo = "Ut aliquid voluptatibus inventore numquam velit eveniet.",
                            EndBookDate = new DateTime(2023, 10, 4, 14, 19, 34, 153, DateTimeKind.Local).AddTicks(4139),
                            ReserveNumber = 806055730,
                            RoomId = 208,
                            StartBookDate = new DateTime(2023, 10, 2, 3, 51, 49, 410, DateTimeKind.Local).AddTicks(2644),
                            UserId = new Guid("3908f980-87ab-bf50-0865-df7d03d6a76b")
                        },
                        new
                        {
                            Id = 267,
                            AdditionalInfo = "Ut ullam aut dicta quia nulla sint unde et ipsam.",
                            EndBookDate = new DateTime(2023, 10, 7, 12, 44, 35, 547, DateTimeKind.Local).AddTicks(3860),
                            ReserveNumber = 724885667,
                            RoomId = 215,
                            StartBookDate = new DateTime(2023, 9, 30, 21, 39, 24, 63, DateTimeKind.Local).AddTicks(8025),
                            UserId = new Guid("387d57a1-5db9-2c43-07d8-f5791de895ca")
                        },
                        new
                        {
                            Id = 268,
                            AdditionalInfo = "Nihil blanditiis expedita recusandae beatae vitae unde qui sequi distinctio.",
                            EndBookDate = new DateTime(2023, 10, 3, 21, 18, 42, 28, DateTimeKind.Local).AddTicks(2759),
                            ReserveNumber = 264566886,
                            RoomId = 242,
                            StartBookDate = new DateTime(2023, 10, 2, 1, 44, 53, 726, DateTimeKind.Local).AddTicks(6086),
                            UserId = new Guid("301f6b8f-b0e6-acd6-77ac-d1cb814ec4bb")
                        },
                        new
                        {
                            Id = 269,
                            AdditionalInfo = "In iste repudiandae.",
                            EndBookDate = new DateTime(2023, 10, 3, 18, 1, 34, 90, DateTimeKind.Local).AddTicks(2111),
                            ReserveNumber = 549521613,
                            RoomId = 210,
                            StartBookDate = new DateTime(2023, 10, 1, 0, 42, 14, 608, DateTimeKind.Local).AddTicks(3692),
                            UserId = new Guid("6ab27978-5a9e-d6e0-b65a-3db61b4c9ba5")
                        },
                        new
                        {
                            Id = 270,
                            AdditionalInfo = "At debitis qui est minus.",
                            EndBookDate = new DateTime(2023, 10, 3, 22, 16, 25, 257, DateTimeKind.Local).AddTicks(3368),
                            ReserveNumber = 564137944,
                            RoomId = 218,
                            StartBookDate = new DateTime(2023, 10, 1, 15, 47, 6, 210, DateTimeKind.Local).AddTicks(4193),
                            UserId = new Guid("89f2361c-b854-0d97-9fe1-572c86b33a5b")
                        },
                        new
                        {
                            Id = 271,
                            AdditionalInfo = "Ut voluptas doloremque quod quisquam vel cumque ut dolores vitae.",
                            EndBookDate = new DateTime(2023, 10, 6, 4, 51, 3, 721, DateTimeKind.Local).AddTicks(5594),
                            ReserveNumber = 822669786,
                            RoomId = 212,
                            StartBookDate = new DateTime(2023, 10, 2, 8, 22, 54, 819, DateTimeKind.Local).AddTicks(9307),
                            UserId = new Guid("301f6b8f-b0e6-acd6-77ac-d1cb814ec4bb")
                        },
                        new
                        {
                            Id = 272,
                            AdditionalInfo = "Porro ad nesciunt sit iste magnam voluptatum exercitationem est.",
                            EndBookDate = new DateTime(2023, 10, 7, 9, 4, 17, 866, DateTimeKind.Local).AddTicks(6753),
                            ReserveNumber = 441861603,
                            RoomId = 203,
                            StartBookDate = new DateTime(2023, 9, 29, 10, 30, 25, 327, DateTimeKind.Local).AddTicks(9816),
                            UserId = new Guid("6ab27978-5a9e-d6e0-b65a-3db61b4c9ba5")
                        },
                        new
                        {
                            Id = 273,
                            AdditionalInfo = "Aut quia omnis cum adipisci quaerat.",
                            EndBookDate = new DateTime(2023, 10, 3, 23, 31, 16, 950, DateTimeKind.Local).AddTicks(7903),
                            ReserveNumber = 578133688,
                            RoomId = 229,
                            StartBookDate = new DateTime(2023, 9, 29, 6, 46, 31, 909, DateTimeKind.Local).AddTicks(814),
                            UserId = new Guid("0995a8d0-41b6-fbf1-57c3-787eb8f3da23")
                        },
                        new
                        {
                            Id = 274,
                            AdditionalInfo = "Dolorem consequatur aut.",
                            EndBookDate = new DateTime(2023, 10, 6, 5, 14, 17, 867, DateTimeKind.Local).AddTicks(4564),
                            ReserveNumber = 408254191,
                            RoomId = 215,
                            StartBookDate = new DateTime(2023, 9, 29, 18, 30, 26, 510, DateTimeKind.Local).AddTicks(2373),
                            UserId = new Guid("6ee61463-73f9-6222-a33c-904f05f9bfb6")
                        },
                        new
                        {
                            Id = 275,
                            AdditionalInfo = "Fugiat sint nisi a et minus.",
                            EndBookDate = new DateTime(2023, 10, 6, 5, 31, 32, 872, DateTimeKind.Local).AddTicks(5032),
                            ReserveNumber = 706727970,
                            RoomId = 241,
                            StartBookDate = new DateTime(2023, 9, 30, 11, 27, 35, 275, DateTimeKind.Local).AddTicks(794),
                            UserId = new Guid("2ba913f8-75e4-8927-20b6-5363b2272497")
                        },
                        new
                        {
                            Id = 276,
                            AdditionalInfo = "Officiis eaque eligendi omnis ut.",
                            EndBookDate = new DateTime(2023, 10, 6, 1, 25, 23, 216, DateTimeKind.Local).AddTicks(7167),
                            ReserveNumber = 678401239,
                            RoomId = 219,
                            StartBookDate = new DateTime(2023, 10, 1, 23, 33, 43, 386, DateTimeKind.Local).AddTicks(9288),
                            UserId = new Guid("c280a1a1-85c4-18f5-0fb4-6f762e6cfc54")
                        },
                        new
                        {
                            Id = 277,
                            AdditionalInfo = "Cum quia sint.",
                            EndBookDate = new DateTime(2023, 10, 4, 14, 58, 31, 408, DateTimeKind.Local).AddTicks(6705),
                            ReserveNumber = 206568806,
                            RoomId = 247,
                            StartBookDate = new DateTime(2023, 10, 1, 1, 59, 31, 605, DateTimeKind.Local).AddTicks(666),
                            UserId = new Guid("440d27e8-af1f-eb57-892c-b7aa51baa431")
                        },
                        new
                        {
                            Id = 278,
                            AdditionalInfo = "Illum sit corrupti a.",
                            EndBookDate = new DateTime(2023, 10, 6, 17, 57, 33, 263, DateTimeKind.Local).AddTicks(8387),
                            ReserveNumber = 693153840,
                            RoomId = 227,
                            StartBookDate = new DateTime(2023, 9, 29, 8, 23, 52, 968, DateTimeKind.Local).AddTicks(6479),
                            UserId = new Guid("ed28bdfc-ad3e-7851-6767-f6e975701306")
                        },
                        new
                        {
                            Id = 279,
                            AdditionalInfo = "Blanditiis architecto qui quia at.",
                            EndBookDate = new DateTime(2023, 10, 5, 5, 16, 42, 23, DateTimeKind.Local).AddTicks(8179),
                            ReserveNumber = 495161670,
                            RoomId = 247,
                            StartBookDate = new DateTime(2023, 9, 28, 23, 26, 49, 523, DateTimeKind.Local).AddTicks(6635),
                            UserId = new Guid("b92d4a6b-a12c-4598-dcd4-871e6d2c934f")
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ed46c73-8ce8-85b7-c133-fdf77b3dcc72"),
                            Email = "Madelyn.Abernathy@yahoo.com",
                            Name = "Nayeli Sanford",
                            Phone = "1-921-368-1598"
                        },
                        new
                        {
                            Id = new Guid("c75353e1-4897-1cdd-4316-3209d80c7194"),
                            Email = "Viva_Jacobson@yahoo.com",
                            Name = "Alvah Stracke",
                            Phone = "342-364-8947"
                        },
                        new
                        {
                            Id = new Guid("2d2db7af-4fdf-d5c2-a5d2-78a81d06db52"),
                            Email = "Candida.Lueilwitz@hotmail.com",
                            Name = "Heidi Fisher",
                            Phone = "626-799-9186"
                        },
                        new
                        {
                            Id = new Guid("48f7f533-3865-99bf-8896-e413964cb90a"),
                            Email = "Louvenia.Fadel44@gmail.com",
                            Name = "Flavio Feeney",
                            Phone = "654.469.3792 x9004"
                        },
                        new
                        {
                            Id = new Guid("66478e62-d40e-789a-b8ab-cc2bdc79e342"),
                            Email = "Alverta.Murazik25@hotmail.com",
                            Name = "Forest Ferry",
                            Phone = "641-336-0379 x4322"
                        },
                        new
                        {
                            Id = new Guid("f1049081-1403-0488-9fa4-f95b69f1b191"),
                            Email = "Ricardo.OReilly73@yahoo.com",
                            Name = "Billie Gaylord",
                            Phone = "1-664-554-9537 x17393"
                        },
                        new
                        {
                            Id = new Guid("b92d4a6b-a12c-4598-dcd4-871e6d2c934f"),
                            Email = "Kattie29@hotmail.com",
                            Name = "Ubaldo Turner",
                            Phone = "1-610-319-9092 x3222"
                        },
                        new
                        {
                            Id = new Guid("aad6457c-9eb8-a840-7f54-189a0af67c91"),
                            Email = "Linnie_Carter97@hotmail.com",
                            Name = "Bianka Boyle",
                            Phone = "941.769.3064 x73607"
                        },
                        new
                        {
                            Id = new Guid("71eef133-3ef7-49cc-0c42-4eaaccc89705"),
                            Email = "Ronaldo.Metz@yahoo.com",
                            Name = "Carmen Labadie",
                            Phone = "(662) 999-1018 x4604"
                        },
                        new
                        {
                            Id = new Guid("eae7cd06-ca5b-a64d-061d-c20426daa476"),
                            Email = "Solon_Nicolas@yahoo.com",
                            Name = "Piper Grimes",
                            Phone = "1-593-452-9503 x9259"
                        },
                        new
                        {
                            Id = new Guid("8e41ef3a-562a-c29a-b177-45cd59651579"),
                            Email = "Kallie.Glover@gmail.com",
                            Name = "Nels Heathcote",
                            Phone = "302-828-8487"
                        },
                        new
                        {
                            Id = new Guid("62d0d675-a8ec-4426-6b66-2b92b0adcfa5"),
                            Email = "Providenci.Volkman@hotmail.com",
                            Name = "Gerald Bode",
                            Phone = "(263) 972-1008"
                        },
                        new
                        {
                            Id = new Guid("2a067fc5-c680-cced-fc81-9dd72b0ac453"),
                            Email = "Lauryn.Haley97@gmail.com",
                            Name = "Elenora Larson",
                            Phone = "1-764-883-4443"
                        },
                        new
                        {
                            Id = new Guid("8b38ffb3-4948-249f-f254-1e0930f4dd94"),
                            Email = "Rosalyn_Muller@gmail.com",
                            Name = "Nicole Schulist",
                            Phone = "(824) 956-2040 x69453"
                        },
                        new
                        {
                            Id = new Guid("0a0f6e51-64c8-4279-0a76-28e0599e27e8"),
                            Email = "Adan.Gottlieb51@yahoo.com",
                            Name = "Valentina Hegmann",
                            Phone = "662-255-2543"
                        },
                        new
                        {
                            Id = new Guid("440d27e8-af1f-eb57-892c-b7aa51baa431"),
                            Email = "Conor_Mitchell77@yahoo.com",
                            Name = "Rosanna Kuhn",
                            Phone = "332.339.7024"
                        },
                        new
                        {
                            Id = new Guid("ed28bdfc-ad3e-7851-6767-f6e975701306"),
                            Email = "Elmo_Padberg82@yahoo.com",
                            Name = "Cale Wuckert",
                            Phone = "(349) 390-0755 x3842"
                        },
                        new
                        {
                            Id = new Guid("a48a8775-b3d3-e2b3-f72e-a5c1a381d52c"),
                            Email = "Murphy.Tillman@hotmail.com",
                            Name = "Sigrid Pouros",
                            Phone = "687-958-0771"
                        },
                        new
                        {
                            Id = new Guid("2864e86c-7311-2523-8416-29b846f4f258"),
                            Email = "Anahi_Heaney60@hotmail.com",
                            Name = "Yvonne Olson",
                            Phone = "764.727.5736 x042"
                        },
                        new
                        {
                            Id = new Guid("16b7ff57-2639-4833-1927-2c09264eed96"),
                            Email = "Phoebe.Fritsch@gmail.com",
                            Name = "Kylee Oberbrunner",
                            Phone = "(760) 536-8579"
                        },
                        new
                        {
                            Id = new Guid("31ffabaa-aad1-e0ad-769a-720d4596c479"),
                            Email = "Clare96@yahoo.com",
                            Name = "Jacey Harvey",
                            Phone = "324-329-6844"
                        },
                        new
                        {
                            Id = new Guid("05d6602e-2587-6aa9-984e-78f7c27f18e6"),
                            Email = "Lindsey.Jacobson84@hotmail.com",
                            Name = "Teresa Ratke",
                            Phone = "1-848-333-6600 x178"
                        },
                        new
                        {
                            Id = new Guid("673941a4-ef1a-e208-c2c2-376925c67788"),
                            Email = "Dejon.Bogan49@gmail.com",
                            Name = "Reilly Daniel",
                            Phone = "(461) 463-5538 x385"
                        },
                        new
                        {
                            Id = new Guid("89196c93-907f-d373-6dc8-0e2ef31099a5"),
                            Email = "Frederique_Runolfsson@hotmail.com",
                            Name = "Buck Reilly",
                            Phone = "587-396-4500"
                        },
                        new
                        {
                            Id = new Guid("d2594fcb-4366-4953-53bc-fd2444cd9feb"),
                            Email = "Jude.Harber81@hotmail.com",
                            Name = "Clement Feeney",
                            Phone = "(676) 738-2242"
                        },
                        new
                        {
                            Id = new Guid("387d57a1-5db9-2c43-07d8-f5791de895ca"),
                            Email = "Kimberly99@yahoo.com",
                            Name = "Maddison Waelchi",
                            Phone = "(884) 715-2778 x734"
                        },
                        new
                        {
                            Id = new Guid("a9e86e7d-a75e-c926-6ba7-ff0811536b60"),
                            Email = "Vladimir_Torphy@yahoo.com",
                            Name = "Tony Abshire",
                            Phone = "996.963.2456 x035"
                        },
                        new
                        {
                            Id = new Guid("548aea95-6c0a-5a10-ee77-fb44cf1b41cf"),
                            Email = "Lazaro.Koepp@gmail.com",
                            Name = "Ayden Padberg",
                            Phone = "959-911-8992 x53601"
                        },
                        new
                        {
                            Id = new Guid("89f2361c-b854-0d97-9fe1-572c86b33a5b"),
                            Email = "Cristal.Brown@hotmail.com",
                            Name = "Arnoldo Towne",
                            Phone = "730-557-1986 x1256"
                        },
                        new
                        {
                            Id = new Guid("eb6a362a-3355-f30e-18f9-dc5d373048a6"),
                            Email = "Abner_Kunde@yahoo.com",
                            Name = "Aurelio Donnelly",
                            Phone = "(251) 463-9554 x4710"
                        },
                        new
                        {
                            Id = new Guid("3908f980-87ab-bf50-0865-df7d03d6a76b"),
                            Email = "Jerome_Hegmann@yahoo.com",
                            Name = "Makayla Okuneva",
                            Phone = "1-577-204-4283 x204"
                        },
                        new
                        {
                            Id = new Guid("326d0d7e-5648-20c2-df30-8fb3b9848611"),
                            Email = "Ashtyn_Rolfson@gmail.com",
                            Name = "Zion Crona",
                            Phone = "(498) 689-1441"
                        },
                        new
                        {
                            Id = new Guid("2c69cb74-3172-5b78-42b9-55dad7bdd9d3"),
                            Email = "Annabelle76@gmail.com",
                            Name = "Maryse McKenzie",
                            Phone = "(605) 743-6767 x773"
                        },
                        new
                        {
                            Id = new Guid("36c683a0-9d39-5aad-6010-ef615fa8a13d"),
                            Email = "Loraine.Hansen93@gmail.com",
                            Name = "Misty Nader",
                            Phone = "331.363.4012 x660"
                        },
                        new
                        {
                            Id = new Guid("bc43d721-27c9-65e6-a1f7-05e6efa2a91b"),
                            Email = "Lavinia_Hammes@gmail.com",
                            Name = "Alberto Stoltenberg",
                            Phone = "1-531-934-5988"
                        },
                        new
                        {
                            Id = new Guid("5379cefc-3ca2-f341-03ef-99354befd137"),
                            Email = "Claudie42@hotmail.com",
                            Name = "Molly Murazik",
                            Phone = "804.834.5246 x947"
                        },
                        new
                        {
                            Id = new Guid("9c6fffd2-a06d-6c70-e989-c2ea46fed991"),
                            Email = "Vivien53@yahoo.com",
                            Name = "Sam Grant",
                            Phone = "1-391-908-6676 x903"
                        },
                        new
                        {
                            Id = new Guid("b73aea00-de4f-e828-915c-64f1a2c5a4a5"),
                            Email = "Lane.Runolfsdottir@yahoo.com",
                            Name = "Jarrell Nitzsche",
                            Phone = "946.466.6049 x2090"
                        },
                        new
                        {
                            Id = new Guid("f47da34c-dc91-ea31-9081-5a86b22cc753"),
                            Email = "Branson_Barton@yahoo.com",
                            Name = "Kellen Monahan",
                            Phone = "704-224-9691 x086"
                        },
                        new
                        {
                            Id = new Guid("1da1b08e-3f44-e30e-7b35-255aa9c87879"),
                            Email = "Keshaun.Carter67@gmail.com",
                            Name = "Shyann Schuster",
                            Phone = "211-561-7346 x58319"
                        },
                        new
                        {
                            Id = new Guid("cc0c698d-5962-4d57-2b83-5bfe4003d056"),
                            Email = "Marjorie.Hahn24@hotmail.com",
                            Name = "Audie O'Connell",
                            Phone = "790-375-3330"
                        },
                        new
                        {
                            Id = new Guid("5d64a3a9-4ec1-d098-a192-e1cf1d1cabdd"),
                            Email = "Ottis31@yahoo.com",
                            Name = "Rosendo Simonis",
                            Phone = "540-755-1670 x9243"
                        },
                        new
                        {
                            Id = new Guid("0995a8d0-41b6-fbf1-57c3-787eb8f3da23"),
                            Email = "Michel_Gaylord@hotmail.com",
                            Name = "Arvel Gutmann",
                            Phone = "840-394-6626 x73403"
                        },
                        new
                        {
                            Id = new Guid("1069d293-a62e-c413-abdc-f8e35545865d"),
                            Email = "Tito.Stoltenberg@yahoo.com",
                            Name = "Gerard Roob",
                            Phone = "957.813.3287 x7768"
                        },
                        new
                        {
                            Id = new Guid("c280a1a1-85c4-18f5-0fb4-6f762e6cfc54"),
                            Email = "Judy_Doyle@hotmail.com",
                            Name = "Arvel Heathcote",
                            Phone = "1-559-477-4919 x78267"
                        },
                        new
                        {
                            Id = new Guid("472340dc-2379-2da3-6f5b-c31c77d42679"),
                            Email = "Shyann.Stroman@gmail.com",
                            Name = "Estefania O'Conner",
                            Phone = "955-210-3339 x346"
                        },
                        new
                        {
                            Id = new Guid("406c8a2a-2200-1ab7-7e98-d4d859fc98e4"),
                            Email = "Dannie.Bruen91@hotmail.com",
                            Name = "Monserrate Buckridge",
                            Phone = "342.877.7164 x94351"
                        },
                        new
                        {
                            Id = new Guid("daedd527-085a-f1f3-66a9-c672f836ca44"),
                            Email = "Kylee.Nolan21@gmail.com",
                            Name = "Chanelle Wisozk",
                            Phone = "1-998-656-5447"
                        },
                        new
                        {
                            Id = new Guid("301f6b8f-b0e6-acd6-77ac-d1cb814ec4bb"),
                            Email = "Eduardo_Tremblay@gmail.com",
                            Name = "Fletcher Zemlak",
                            Phone = "742-617-9912"
                        },
                        new
                        {
                            Id = new Guid("2a3e215c-d52b-0f32-74f0-773d3688f729"),
                            Email = "Sage.Mante@gmail.com",
                            Name = "Ned Rath",
                            Phone = "1-424-753-0536 x3671"
                        },
                        new
                        {
                            Id = new Guid("6ab27978-5a9e-d6e0-b65a-3db61b4c9ba5"),
                            Email = "Joel_Yundt@hotmail.com",
                            Name = "Hunter Carroll",
                            Phone = "(334) 444-7136"
                        },
                        new
                        {
                            Id = new Guid("54f32fd5-cbc6-ad9b-9713-ab52c09df94b"),
                            Email = "Maximillia76@hotmail.com",
                            Name = "Craig Auer",
                            Phone = "(818) 341-4482 x41826"
                        },
                        new
                        {
                            Id = new Guid("562deb07-ac26-5451-ad53-804d96ee049c"),
                            Email = "Grayson75@yahoo.com",
                            Name = "Enos Romaguera",
                            Phone = "(973) 614-8529 x207"
                        },
                        new
                        {
                            Id = new Guid("587f2784-18a0-27a5-c444-364b48c21984"),
                            Email = "Robyn43@yahoo.com",
                            Name = "Burnice Funk",
                            Phone = "582-730-1298 x896"
                        },
                        new
                        {
                            Id = new Guid("6ee61463-73f9-6222-a33c-904f05f9bfb6"),
                            Email = "Helga12@yahoo.com",
                            Name = "Anabel Towne",
                            Phone = "886-563-7673 x9714"
                        },
                        new
                        {
                            Id = new Guid("2ba913f8-75e4-8927-20b6-5363b2272497"),
                            Email = "Durward.Bechtelar@hotmail.com",
                            Name = "General Lubowitz",
                            Phone = "337.616.3810"
                        },
                        new
                        {
                            Id = new Guid("3382e1a3-9c29-5ad2-89a2-7850df352f40"),
                            Email = "Madison_Graham@hotmail.com",
                            Name = "Francisca Grady",
                            Phone = "(656) 902-5785 x2201"
                        },
                        new
                        {
                            Id = new Guid("b5285536-a394-d62c-6336-7e34acd1b74b"),
                            Email = "Karina50@yahoo.com",
                            Name = "Donnell Schroeder",
                            Phone = "773-922-9774 x75045"
                        },
                        new
                        {
                            Id = new Guid("3ce42bb1-add6-669d-6738-15398c0f20e2"),
                            Email = "Irving_Swift72@yahoo.com",
                            Name = "Waldo Fisher",
                            Phone = "938.680.1967 x692"
                        },
                        new
                        {
                            Id = new Guid("e4d28bcd-c9dc-bb3e-f45c-a8fc1998a306"),
                            Email = "Bo83@yahoo.com",
                            Name = "Ottilie Morar",
                            Phone = "251-662-9197"
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.RoomReserve", b =>
                {
                    b.HasOne("HotelReserveAppServer.Models.Room", "Room")
                        .WithMany("RoomReserves")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReserveAppServer.Models.User", "User")
                        .WithMany("Reserves")
                        .HasForeignKey("UserId");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.Room", b =>
                {
                    b.Navigation("RoomReserves");
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.User", b =>
                {
                    b.Navigation("Reserves");
                });
#pragma warning restore 612, 618
        }
    }
}
