// <auto-generated />
using System;
using HotelReserveAppServer.Controllers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelReserveAppServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelReserveAppServer.Models.ReserveDateInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndBookDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReserveNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartBookDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("ReserveDateIntervals");

                    b.HasData(
                        new
                        {
                            Id = 250,
                            EndBookDate = new DateTime(2023, 10, 1, 17, 55, 3, 663, DateTimeKind.Local).AddTicks(7496),
                            ReserveNumber = 402867881,
                            RoomId = 209,
                            StartBookDate = new DateTime(2023, 9, 28, 13, 5, 10, 153, DateTimeKind.Local).AddTicks(4100),
                            UserId = new Guid("3e7435d3-515d-76ee-e1ef-148e57fbde34")
                        },
                        new
                        {
                            Id = 251,
                            EndBookDate = new DateTime(2023, 10, 3, 3, 17, 13, 990, DateTimeKind.Local).AddTicks(2337),
                            ReserveNumber = 636150619,
                            RoomId = 217,
                            StartBookDate = new DateTime(2023, 9, 28, 8, 42, 54, 242, DateTimeKind.Local).AddTicks(2588),
                            UserId = new Guid("8f4dd10d-9fff-5257-be4c-73d8826b172f")
                        },
                        new
                        {
                            Id = 252,
                            EndBookDate = new DateTime(2023, 10, 4, 5, 54, 50, 963, DateTimeKind.Local).AddTicks(6032),
                            ReserveNumber = 124985454,
                            RoomId = 206,
                            StartBookDate = new DateTime(2023, 9, 27, 18, 51, 23, 843, DateTimeKind.Local).AddTicks(6525),
                            UserId = new Guid("16d47301-a097-2bb9-dda4-2024ebe75fe5")
                        },
                        new
                        {
                            Id = 253,
                            EndBookDate = new DateTime(2023, 10, 3, 9, 35, 20, 562, DateTimeKind.Local).AddTicks(4685),
                            ReserveNumber = 625687639,
                            RoomId = 200,
                            StartBookDate = new DateTime(2023, 9, 27, 7, 53, 19, 319, DateTimeKind.Local).AddTicks(4977),
                            UserId = new Guid("e2a33b09-5555-6453-5a21-2029d34c4f4d")
                        },
                        new
                        {
                            Id = 254,
                            EndBookDate = new DateTime(2023, 10, 3, 15, 38, 30, 610, DateTimeKind.Local).AddTicks(9355),
                            ReserveNumber = 621140258,
                            RoomId = 214,
                            StartBookDate = new DateTime(2023, 9, 26, 18, 8, 27, 531, DateTimeKind.Local).AddTicks(8613),
                            UserId = new Guid("16d47301-a097-2bb9-dda4-2024ebe75fe5")
                        },
                        new
                        {
                            Id = 255,
                            EndBookDate = new DateTime(2023, 10, 4, 14, 14, 18, 529, DateTimeKind.Local).AddTicks(7828),
                            ReserveNumber = 450220778,
                            RoomId = 210,
                            StartBookDate = new DateTime(2023, 9, 27, 7, 51, 32, 594, DateTimeKind.Local).AddTicks(9263),
                            UserId = new Guid("9daeb3a9-ab2b-b2b4-9005-8ff5d2c1acb5")
                        },
                        new
                        {
                            Id = 256,
                            EndBookDate = new DateTime(2023, 10, 2, 3, 27, 46, 981, DateTimeKind.Local).AddTicks(8415),
                            ReserveNumber = 650484819,
                            RoomId = 206,
                            StartBookDate = new DateTime(2023, 9, 29, 11, 3, 59, 630, DateTimeKind.Local).AddTicks(1905),
                            UserId = new Guid("01004997-3b8d-9c82-42b7-aba45cea6ebb")
                        },
                        new
                        {
                            Id = 257,
                            EndBookDate = new DateTime(2023, 10, 2, 15, 10, 21, 949, DateTimeKind.Local).AddTicks(668),
                            ReserveNumber = 734233739,
                            RoomId = 236,
                            StartBookDate = new DateTime(2023, 9, 29, 1, 51, 55, 560, DateTimeKind.Local).AddTicks(5324),
                            UserId = new Guid("34ef4eaf-fd02-6dd4-9bbe-6a13f70439aa")
                        },
                        new
                        {
                            Id = 258,
                            EndBookDate = new DateTime(2023, 10, 2, 0, 28, 51, 34, DateTimeKind.Local).AddTicks(6561),
                            ReserveNumber = 414850620,
                            RoomId = 236,
                            StartBookDate = new DateTime(2023, 9, 25, 23, 0, 58, 985, DateTimeKind.Local).AddTicks(2147),
                            UserId = new Guid("16d47301-a097-2bb9-dda4-2024ebe75fe5")
                        },
                        new
                        {
                            Id = 259,
                            EndBookDate = new DateTime(2023, 10, 1, 3, 31, 3, 137, DateTimeKind.Local).AddTicks(7753),
                            ReserveNumber = 100863539,
                            RoomId = 249,
                            StartBookDate = new DateTime(2023, 9, 29, 1, 11, 38, 712, DateTimeKind.Local).AddTicks(4310),
                            UserId = new Guid("729ecf93-7447-100b-d630-3605cec8f89b")
                        },
                        new
                        {
                            Id = 260,
                            EndBookDate = new DateTime(2023, 10, 3, 16, 33, 33, 544, DateTimeKind.Local).AddTicks(1311),
                            ReserveNumber = 892020265,
                            RoomId = 214,
                            StartBookDate = new DateTime(2023, 9, 28, 14, 34, 9, 858, DateTimeKind.Local).AddTicks(5043),
                            UserId = new Guid("4bc8dc7e-3d7a-308f-fa78-e745109195b5")
                        },
                        new
                        {
                            Id = 261,
                            EndBookDate = new DateTime(2023, 10, 1, 2, 3, 42, 337, DateTimeKind.Local).AddTicks(9820),
                            ReserveNumber = 287359861,
                            RoomId = 207,
                            StartBookDate = new DateTime(2023, 9, 28, 15, 3, 14, 992, DateTimeKind.Local).AddTicks(5260),
                            UserId = new Guid("4bc8dc7e-3d7a-308f-fa78-e745109195b5")
                        },
                        new
                        {
                            Id = 262,
                            EndBookDate = new DateTime(2023, 10, 1, 16, 15, 31, 770, DateTimeKind.Local).AddTicks(8292),
                            ReserveNumber = 490396209,
                            RoomId = 224,
                            StartBookDate = new DateTime(2023, 9, 25, 18, 6, 41, 556, DateTimeKind.Local).AddTicks(4581),
                            UserId = new Guid("7cca1a4b-263a-ce54-8e88-416c018b5d1a")
                        },
                        new
                        {
                            Id = 263,
                            EndBookDate = new DateTime(2023, 10, 3, 10, 39, 40, 220, DateTimeKind.Local).AddTicks(8532),
                            ReserveNumber = 430642999,
                            RoomId = 227,
                            StartBookDate = new DateTime(2023, 9, 27, 13, 46, 35, 307, DateTimeKind.Local).AddTicks(5936),
                            UserId = new Guid("886fc39a-68f2-5020-2b80-89e3cb6b3d6c")
                        },
                        new
                        {
                            Id = 264,
                            EndBookDate = new DateTime(2023, 10, 1, 22, 51, 35, 781, DateTimeKind.Local).AddTicks(2765),
                            ReserveNumber = 868571628,
                            RoomId = 241,
                            StartBookDate = new DateTime(2023, 9, 26, 0, 19, 50, 879, DateTimeKind.Local).AddTicks(3333),
                            UserId = new Guid("f4e14888-4302-43a5-0dce-ea9d30fac86c")
                        },
                        new
                        {
                            Id = 265,
                            EndBookDate = new DateTime(2023, 9, 30, 22, 13, 49, 737, DateTimeKind.Local).AddTicks(773),
                            ReserveNumber = 206730630,
                            RoomId = 218,
                            StartBookDate = new DateTime(2023, 9, 27, 2, 56, 34, 269, DateTimeKind.Local).AddTicks(8944),
                            UserId = new Guid("fc79119c-64dd-182d-9ada-c211a8f5a7a6")
                        },
                        new
                        {
                            Id = 266,
                            EndBookDate = new DateTime(2023, 9, 30, 18, 41, 6, 456, DateTimeKind.Local).AddTicks(847),
                            ReserveNumber = 323625045,
                            RoomId = 239,
                            StartBookDate = new DateTime(2023, 9, 28, 1, 34, 8, 6, DateTimeKind.Local).AddTicks(7928),
                            UserId = new Guid("af874ea1-c33c-b234-715d-29c06b0143ae")
                        },
                        new
                        {
                            Id = 267,
                            EndBookDate = new DateTime(2023, 10, 2, 11, 42, 16, 796, DateTimeKind.Local).AddTicks(9624),
                            ReserveNumber = 250078850,
                            RoomId = 211,
                            StartBookDate = new DateTime(2023, 9, 28, 11, 44, 52, 860, DateTimeKind.Local).AddTicks(6472),
                            UserId = new Guid("70004bb4-af13-1c73-baec-dad8b8cfbe66")
                        },
                        new
                        {
                            Id = 268,
                            EndBookDate = new DateTime(2023, 10, 3, 7, 17, 55, 462, DateTimeKind.Local).AddTicks(5939),
                            ReserveNumber = 416780063,
                            RoomId = 248,
                            StartBookDate = new DateTime(2023, 9, 28, 11, 38, 29, 819, DateTimeKind.Local).AddTicks(7119),
                            UserId = new Guid("aa25bebc-0b07-d5cc-2f0c-e459bfb51274")
                        },
                        new
                        {
                            Id = 269,
                            EndBookDate = new DateTime(2023, 10, 3, 10, 57, 41, 531, DateTimeKind.Local).AddTicks(7021),
                            ReserveNumber = 293795575,
                            RoomId = 228,
                            StartBookDate = new DateTime(2023, 9, 29, 4, 5, 25, 36, DateTimeKind.Local).AddTicks(9698),
                            UserId = new Guid("f4e14888-4302-43a5-0dce-ea9d30fac86c")
                        },
                        new
                        {
                            Id = 270,
                            EndBookDate = new DateTime(2023, 9, 30, 22, 25, 39, 960, DateTimeKind.Local).AddTicks(8270),
                            ReserveNumber = 100756061,
                            RoomId = 200,
                            StartBookDate = new DateTime(2023, 9, 28, 1, 35, 36, 144, DateTimeKind.Local).AddTicks(1939),
                            UserId = new Guid("969401c8-9890-5ba2-0780-0d23467bc909")
                        },
                        new
                        {
                            Id = 271,
                            EndBookDate = new DateTime(2023, 10, 1, 19, 42, 18, 585, DateTimeKind.Local).AddTicks(5095),
                            ReserveNumber = 864470094,
                            RoomId = 220,
                            StartBookDate = new DateTime(2023, 9, 26, 21, 52, 34, 337, DateTimeKind.Local).AddTicks(1687),
                            UserId = new Guid("87d97a0e-1b41-4bf0-8680-eab62820410c")
                        },
                        new
                        {
                            Id = 272,
                            EndBookDate = new DateTime(2023, 10, 1, 5, 35, 56, 185, DateTimeKind.Local).AddTicks(3439),
                            ReserveNumber = 793342651,
                            RoomId = 222,
                            StartBookDate = new DateTime(2023, 9, 28, 1, 17, 33, 938, DateTimeKind.Local).AddTicks(7634),
                            UserId = new Guid("886fc39a-68f2-5020-2b80-89e3cb6b3d6c")
                        },
                        new
                        {
                            Id = 273,
                            EndBookDate = new DateTime(2023, 10, 2, 16, 18, 48, 660, DateTimeKind.Local).AddTicks(8386),
                            ReserveNumber = 533797988,
                            RoomId = 202,
                            StartBookDate = new DateTime(2023, 9, 27, 22, 17, 21, 321, DateTimeKind.Local).AddTicks(6724),
                            UserId = new Guid("70004bb4-af13-1c73-baec-dad8b8cfbe66")
                        },
                        new
                        {
                            Id = 274,
                            EndBookDate = new DateTime(2023, 10, 1, 1, 14, 10, 702, DateTimeKind.Local).AddTicks(4505),
                            ReserveNumber = 758044915,
                            RoomId = 201,
                            StartBookDate = new DateTime(2023, 9, 25, 18, 32, 29, 958, DateTimeKind.Local).AddTicks(7781),
                            UserId = new Guid("bd2b577b-b3c2-d620-cc57-2f3f42cbeedd")
                        },
                        new
                        {
                            Id = 275,
                            EndBookDate = new DateTime(2023, 10, 3, 13, 22, 41, 175, DateTimeKind.Local).AddTicks(5325),
                            ReserveNumber = 840561790,
                            RoomId = 201,
                            StartBookDate = new DateTime(2023, 9, 27, 6, 26, 16, 778, DateTimeKind.Local).AddTicks(2501),
                            UserId = new Guid("bd2b577b-b3c2-d620-cc57-2f3f42cbeedd")
                        },
                        new
                        {
                            Id = 276,
                            EndBookDate = new DateTime(2023, 10, 2, 5, 26, 57, 217, DateTimeKind.Local).AddTicks(8314),
                            ReserveNumber = 467123831,
                            RoomId = 232,
                            StartBookDate = new DateTime(2023, 9, 26, 14, 50, 6, 91, DateTimeKind.Local).AddTicks(6195),
                            UserId = new Guid("26b7ccbf-3d85-71b7-d6f9-259d64b90591")
                        },
                        new
                        {
                            Id = 277,
                            EndBookDate = new DateTime(2023, 10, 2, 19, 27, 59, 301, DateTimeKind.Local).AddTicks(3518),
                            ReserveNumber = 711428566,
                            RoomId = 206,
                            StartBookDate = new DateTime(2023, 9, 26, 14, 1, 56, 99, DateTimeKind.Local).AddTicks(3492),
                            UserId = new Guid("729ecf93-7447-100b-d630-3605cec8f89b")
                        },
                        new
                        {
                            Id = 278,
                            EndBookDate = new DateTime(2023, 10, 3, 11, 23, 43, 96, DateTimeKind.Local).AddTicks(3773),
                            ReserveNumber = 625515964,
                            RoomId = 211,
                            StartBookDate = new DateTime(2023, 9, 28, 9, 24, 31, 354, DateTimeKind.Local).AddTicks(7278),
                            UserId = new Guid("8bf6c776-186f-0ff6-83b1-5c5646eef071")
                        },
                        new
                        {
                            Id = 279,
                            EndBookDate = new DateTime(2023, 10, 3, 21, 5, 4, 831, DateTimeKind.Local).AddTicks(1443),
                            ReserveNumber = 356053867,
                            RoomId = 200,
                            StartBookDate = new DateTime(2023, 9, 28, 23, 59, 1, 265, DateTimeKind.Local).AddTicks(471),
                            UserId = new Guid("73a66fed-623c-cf11-454f-31dd4d27b10a")
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAmountOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 200,
                            Class = 1,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 1,
                            Number = 292
                        },
                        new
                        {
                            Id = 201,
                            Class = 2,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 6,
                            Number = 363
                        },
                        new
                        {
                            Id = 202,
                            Class = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 6,
                            Number = 157
                        },
                        new
                        {
                            Id = 203,
                            Class = 1,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 5,
                            Number = 356
                        },
                        new
                        {
                            Id = 204,
                            Class = 1,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 3,
                            Number = 296
                        },
                        new
                        {
                            Id = 205,
                            Class = 2,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 1,
                            Number = 194
                        },
                        new
                        {
                            Id = 206,
                            Class = 3,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 5,
                            Number = 276
                        },
                        new
                        {
                            Id = 207,
                            Class = 2,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 3,
                            Number = 283
                        },
                        new
                        {
                            Id = 208,
                            Class = 3,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 4,
                            Number = 209
                        },
                        new
                        {
                            Id = 209,
                            Class = 3,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 3,
                            Number = 186
                        },
                        new
                        {
                            Id = 210,
                            Class = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 2,
                            Number = 477
                        },
                        new
                        {
                            Id = 211,
                            Class = 3,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 6,
                            Number = 308
                        },
                        new
                        {
                            Id = 212,
                            Class = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 6,
                            Number = 482
                        },
                        new
                        {
                            Id = 213,
                            Class = 1,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 1,
                            Number = 243
                        },
                        new
                        {
                            Id = 214,
                            Class = 1,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 5,
                            Number = 335
                        },
                        new
                        {
                            Id = 215,
                            Class = 3,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 1,
                            Number = 480
                        },
                        new
                        {
                            Id = 216,
                            Class = 2,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 6,
                            Number = 332
                        },
                        new
                        {
                            Id = 217,
                            Class = 1,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 2,
                            Number = 183
                        },
                        new
                        {
                            Id = 218,
                            Class = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 3,
                            Number = 157
                        },
                        new
                        {
                            Id = 219,
                            Class = 2,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            MaxAmountOfPeople = 5,
                            Number = 160
                        },
                        new
                        {
                            Id = 220,
                            Class = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 4,
                            Number = 489
                        },
                        new
                        {
                            Id = 221,
                            Class = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 2,
                            Number = 491
                        },
                        new
                        {
                            Id = 222,
                            Class = 3,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 4,
                            Number = 334
                        },
                        new
                        {
                            Id = 223,
                            Class = 3,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            MaxAmountOfPeople = 4,
                            Number = 455
                        },
                        new
                        {
                            Id = 224,
                            Class = 1,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 3,
                            Number = 239
                        },
                        new
                        {
                            Id = 225,
                            Class = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 5,
                            Number = 260
                        },
                        new
                        {
                            Id = 226,
                            Class = 1,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 5,
                            Number = 119
                        },
                        new
                        {
                            Id = 227,
                            Class = 2,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 6,
                            Number = 267
                        },
                        new
                        {
                            Id = 228,
                            Class = 2,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            MaxAmountOfPeople = 4,
                            Number = 273
                        },
                        new
                        {
                            Id = 229,
                            Class = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 1,
                            Number = 226
                        },
                        new
                        {
                            Id = 230,
                            Class = 2,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            MaxAmountOfPeople = 3,
                            Number = 359
                        },
                        new
                        {
                            Id = 231,
                            Class = 3,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            MaxAmountOfPeople = 1,
                            Number = 236
                        },
                        new
                        {
                            Id = 232,
                            Class = 1,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 1,
                            Number = 244
                        },
                        new
                        {
                            Id = 233,
                            Class = 3,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 6,
                            Number = 322
                        },
                        new
                        {
                            Id = 234,
                            Class = 2,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            MaxAmountOfPeople = 5,
                            Number = 128
                        },
                        new
                        {
                            Id = 235,
                            Class = 2,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            MaxAmountOfPeople = 2,
                            Number = 185
                        },
                        new
                        {
                            Id = 236,
                            Class = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 2,
                            Number = 454
                        },
                        new
                        {
                            Id = 237,
                            Class = 2,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 1,
                            Number = 398
                        },
                        new
                        {
                            Id = 238,
                            Class = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 6,
                            Number = 420
                        },
                        new
                        {
                            Id = 239,
                            Class = 1,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 6,
                            Number = 514
                        },
                        new
                        {
                            Id = 240,
                            Class = 1,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 2,
                            Number = 450
                        },
                        new
                        {
                            Id = 241,
                            Class = 1,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            MaxAmountOfPeople = 3,
                            Number = 373
                        },
                        new
                        {
                            Id = 242,
                            Class = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            MaxAmountOfPeople = 1,
                            Number = 519
                        },
                        new
                        {
                            Id = 243,
                            Class = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            MaxAmountOfPeople = 4,
                            Number = 511
                        },
                        new
                        {
                            Id = 244,
                            Class = 2,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 3,
                            Number = 156
                        },
                        new
                        {
                            Id = 245,
                            Class = 3,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            MaxAmountOfPeople = 6,
                            Number = 324
                        },
                        new
                        {
                            Id = 246,
                            Class = 1,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            MaxAmountOfPeople = 3,
                            Number = 240
                        },
                        new
                        {
                            Id = 247,
                            Class = 1,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            MaxAmountOfPeople = 2,
                            Number = 260
                        },
                        new
                        {
                            Id = 248,
                            Class = 2,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 2,
                            Number = 331
                        },
                        new
                        {
                            Id = 249,
                            Class = 3,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            MaxAmountOfPeople = 2,
                            Number = 155
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b34b119c-ec37-aa2b-cf8b-6cbf22223761"),
                            Email = "Kenny_Bartoletti10@hotmail.com",
                            Name = "Kade Morissette",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("73a66fed-623c-cf11-454f-31dd4d27b10a"),
                            Email = "Mavis94@yahoo.com",
                            Name = "Edmund Harvey",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("e2a33b09-5555-6453-5a21-2029d34c4f4d"),
                            Email = "Ressie_Parker62@yahoo.com",
                            Name = "Kasey McCullough",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("7991101b-dd54-1898-9168-df9b3ea8e726"),
                            Email = "Osbaldo_Hirthe49@yahoo.com",
                            Name = "Marlin Hettinger",
                            Phone = "en",
                            UserDescription = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            Id = new Guid("cc45e6ed-1830-7fe9-7b3d-385977d54736"),
                            Email = "Annamae77@hotmail.com",
                            Name = "Domingo Walsh",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("34ef4eaf-fd02-6dd4-9bbe-6a13f70439aa"),
                            Email = "Hillard41@hotmail.com",
                            Name = "Elroy Kemmer",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("7a05e7a7-a98c-90e5-d40c-785a2d7751ec"),
                            Email = "Darrel_McGlynn@hotmail.com",
                            Name = "Erik Feest",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("af874ea1-c33c-b234-715d-29c06b0143ae"),
                            Email = "Tabitha.Swift@gmail.com",
                            Name = "Jeff Cruickshank",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("b07a06ff-72f4-18da-94fd-e25394afd6da"),
                            Email = "Ferne26@yahoo.com",
                            Name = "Calista Upton",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("87d97a0e-1b41-4bf0-8680-eab62820410c"),
                            Email = "Andreane.Schaefer29@yahoo.com",
                            Name = "Beaulah Willms",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("886fc39a-68f2-5020-2b80-89e3cb6b3d6c"),
                            Email = "Elias11@yahoo.com",
                            Name = "Diego Kunze",
                            Phone = "en",
                            UserDescription = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            Id = new Guid("aa25bebc-0b07-d5cc-2f0c-e459bfb51274"),
                            Email = "Gregory70@gmail.com",
                            Name = "Lucious Dickens",
                            Phone = "en",
                            UserDescription = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            Id = new Guid("427a2d73-09f6-8a94-7b75-bacc8d5d3f78"),
                            Email = "Kraig_McKenzie10@hotmail.com",
                            Name = "Zoie Hilll",
                            Phone = "en",
                            UserDescription = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            Id = new Guid("434fb61a-243e-0efa-1b98-98c299753aa8"),
                            Email = "Neoma_Bogisich59@yahoo.com",
                            Name = "Cassie Krajcik",
                            Phone = "en",
                            UserDescription = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016"
                        },
                        new
                        {
                            Id = new Guid("8fe65be8-f988-e11d-dbc9-7e25e2673153"),
                            Email = "Cale_Rowe@gmail.com",
                            Name = "Remington Hauck",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("9daeb3a9-ab2b-b2b4-9005-8ff5d2c1acb5"),
                            Email = "Alden.Torphy@hotmail.com",
                            Name = "Leilani Hoppe",
                            Phone = "en",
                            UserDescription = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            Id = new Guid("729ecf93-7447-100b-d630-3605cec8f89b"),
                            Email = "Eduardo_Torp42@yahoo.com",
                            Name = "Ubaldo McKenzie",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("4eb81be8-c4a1-d131-10a4-40cc3531b6d4"),
                            Email = "Eleanore52@yahoo.com",
                            Name = "Bailee Beier",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("8f5bd60d-7153-eafe-ca72-43e23a21f8ea"),
                            Email = "Zion.Von@yahoo.com",
                            Name = "Elisa Wilderman",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("0a3e15f2-7c94-0326-8bfe-6b31f71a8b8c"),
                            Email = "Christ_Jakubowski@yahoo.com",
                            Name = "Andreane Zieme",
                            Phone = "en",
                            UserDescription = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support"
                        },
                        new
                        {
                            Id = new Guid("26b7ccbf-3d85-71b7-d6f9-259d64b90591"),
                            Email = "Eveline39@gmail.com",
                            Name = "Vincent Pouros",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("16d47301-a097-2bb9-dda4-2024ebe75fe5"),
                            Email = "Milford2@gmail.com",
                            Name = "Kole Rodriguez",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("6a599e8f-b3da-6223-0f3e-1735e48e4435"),
                            Email = "Bettye25@hotmail.com",
                            Name = "Lonie McCullough",
                            Phone = "en",
                            UserDescription = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            Id = new Guid("8f4dd10d-9fff-5257-be4c-73d8826b172f"),
                            Email = "Shad_Nikolaus@yahoo.com",
                            Name = "Vella Rempel",
                            Phone = "en",
                            UserDescription = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            Id = new Guid("bdb1a7e8-8075-beaf-e6b2-e1e41313a58d"),
                            Email = "Helga82@hotmail.com",
                            Name = "Bobbie Blick",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("7cca1a4b-263a-ce54-8e88-416c018b5d1a"),
                            Email = "Nash.Fahey@gmail.com",
                            Name = "Jevon Kessler",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("01004997-3b8d-9c82-42b7-aba45cea6ebb"),
                            Email = "Cindy_Goodwin84@gmail.com",
                            Name = "Lesley Von",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("c674d53a-dd95-a264-5977-350200ec86de"),
                            Email = "Wellington_Kreiger9@gmail.com",
                            Name = "Rodrick Casper",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("f4e14888-4302-43a5-0dce-ea9d30fac86c"),
                            Email = "Jana_Kovacek24@gmail.com",
                            Name = "Vernie Stokes",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("13f7a25b-77c5-87af-ad8e-da0f41e6e977"),
                            Email = "Shea.OReilly30@yahoo.com",
                            Name = "Julianne Daniel",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("97a6c36b-19ff-6f82-4628-292a2707533a"),
                            Email = "Ulises.Monahan91@yahoo.com",
                            Name = "Jocelyn Jacobson",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("da9fc4a8-a176-1dd9-3290-158a3879b4fb"),
                            Email = "Candace75@yahoo.com",
                            Name = "Alejandrin Bruen",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("047316e7-a989-c810-2a3a-c0b29e807ce1"),
                            Email = "Emmet_Cummerata@yahoo.com",
                            Name = "Autumn Hayes",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("2448d271-3551-6d82-4c92-92e109bd8e15"),
                            Email = "Loyce_Johns15@hotmail.com",
                            Name = "Kathryne Mann",
                            Phone = "en",
                            UserDescription = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive"
                        },
                        new
                        {
                            Id = new Guid("70004bb4-af13-1c73-baec-dad8b8cfbe66"),
                            Email = "Petra59@yahoo.com",
                            Name = "Dortha Collins",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("4bc8dc7e-3d7a-308f-fa78-e745109195b5"),
                            Email = "Jonathon6@yahoo.com",
                            Name = "Dean Gleichner",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("c4ed5f5b-d22d-adf8-c3c1-45291e805636"),
                            Email = "Kristoffer.Parisian7@yahoo.com",
                            Name = "Keagan Shanahan",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("a13d70b5-b6c0-10fb-2da2-4c84035409cf"),
                            Email = "Marshall_Kertzmann@gmail.com",
                            Name = "Cruz Muller",
                            Phone = "en",
                            UserDescription = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            Id = new Guid("33f1f5e6-a7c9-12f8-df75-da95c4c828a9"),
                            Email = "Pearlie32@yahoo.com",
                            Name = "Dina Koch",
                            Phone = "en",
                            UserDescription = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016"
                        },
                        new
                        {
                            Id = new Guid("651be192-5aa6-1a3b-97d0-cda1db4d1524"),
                            Email = "Lucienne45@hotmail.com",
                            Name = "Enola Gleichner",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("b620183a-4422-3b9c-4ad9-b2d0f6c615fd"),
                            Email = "Kale.Runte19@hotmail.com",
                            Name = "Jodie Hessel",
                            Phone = "en",
                            UserDescription = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support"
                        },
                        new
                        {
                            Id = new Guid("550380c3-ca8f-86d7-e009-71f7df4308f8"),
                            Email = "Leonor_McLaughlin@gmail.com",
                            Name = "Jamarcus Pfeffer",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("f49946f9-4384-2c67-e201-e74bf1275acf"),
                            Email = "Hellen28@gmail.com",
                            Name = "Hugh Lind",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("ae225792-9eb3-e14f-7788-840df89bc18a"),
                            Email = "Mozell85@yahoo.com",
                            Name = "Oswaldo Weimann",
                            Phone = "en",
                            UserDescription = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            Id = new Guid("52016dfd-56aa-f68f-7842-cdc19ab007b5"),
                            Email = "Ona_Haley@hotmail.com",
                            Name = "Reyes Gottlieb",
                            Phone = "en",
                            UserDescription = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            Id = new Guid("53e99ab1-9f01-2369-71ff-b41b7c433ea6"),
                            Email = "Lina.Murray@gmail.com",
                            Name = "Rubye Buckridge",
                            Phone = "en",
                            UserDescription = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
                        },
                        new
                        {
                            Id = new Guid("3e7435d3-515d-76ee-e1ef-148e57fbde34"),
                            Email = "Madie98@yahoo.com",
                            Name = "Itzel Rippin",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("fc79119c-64dd-182d-9ada-c211a8f5a7a6"),
                            Email = "Torey_Purdy@hotmail.com",
                            Name = "Darrick Lindgren",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        },
                        new
                        {
                            Id = new Guid("bd2b577b-b3c2-d620-cc57-2f3f42cbeedd"),
                            Email = "Lina.Dicki@gmail.com",
                            Name = "Urban Stehr",
                            Phone = "en",
                            UserDescription = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality"
                        },
                        new
                        {
                            Id = new Guid("4e87e18c-4dc3-9737-bb87-f401dc41316a"),
                            Email = "Buford.Watsica@hotmail.com",
                            Name = "Leonardo Waelchi",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("4cabcb15-7728-0b5f-4f8a-67608d0e7f77"),
                            Email = "Charity23@gmail.com",
                            Name = "Johnathon Brakus",
                            Phone = "en",
                            UserDescription = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016"
                        },
                        new
                        {
                            Id = new Guid("fac14815-1dbc-edc8-480f-64a09a60ed0b"),
                            Email = "Dimitri47@gmail.com",
                            Name = "Eda Rogahn",
                            Phone = "en",
                            UserDescription = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals"
                        },
                        new
                        {
                            Id = new Guid("e1a2e03e-e187-fe1b-9c3d-9cc867e56dd1"),
                            Email = "Bernardo22@gmail.com",
                            Name = "Marina Beer",
                            Phone = "en",
                            UserDescription = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit"
                        },
                        new
                        {
                            Id = new Guid("00cc3b5d-491f-0653-ff52-cd888e7fda10"),
                            Email = "Adele_Cartwright@hotmail.com",
                            Name = "Irving McClure",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("40777ab4-9d58-1d07-eaff-07c84f6659fb"),
                            Email = "Dewitt.Bogisich@hotmail.com",
                            Name = "Geo Ondricka",
                            Phone = "en",
                            UserDescription = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J"
                        },
                        new
                        {
                            Id = new Guid("ea4da663-0bfe-2474-1125-980c2c1e0519"),
                            Email = "Chad.Crooks51@yahoo.com",
                            Name = "Tessie D'Amore",
                            Phone = "en",
                            UserDescription = "The Football Is Good For Training And Recreational Purposes"
                        },
                        new
                        {
                            Id = new Guid("5ef8445a-b3fd-8cc9-0cd6-1c56be27ed03"),
                            Email = "Paul_Leffler@yahoo.com",
                            Name = "Onie Huel",
                            Phone = "en",
                            UserDescription = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients"
                        },
                        new
                        {
                            Id = new Guid("8bf6c776-186f-0ff6-83b1-5c5646eef071"),
                            Email = "Eunice39@hotmail.com",
                            Name = "Hillary Feeney",
                            Phone = "en",
                            UserDescription = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support"
                        },
                        new
                        {
                            Id = new Guid("d35375bc-c08b-d27b-d8b3-2fc6dec7b790"),
                            Email = "Ellie.Konopelski@yahoo.com",
                            Name = "Peyton Skiles",
                            Phone = "en",
                            UserDescription = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles"
                        },
                        new
                        {
                            Id = new Guid("969401c8-9890-5ba2-0780-0d23467bc909"),
                            Email = "Adrianna_OKon32@gmail.com",
                            Name = "Sven Nienow",
                            Phone = "en",
                            UserDescription = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design"
                        });
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.ReserveDateInterval", b =>
                {
                    b.HasOne("HotelReserveAppServer.Models.Room", "Room")
                        .WithMany("ReservedDates")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelReserveAppServer.Models.User", "User")
                        .WithMany("Reserves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.Room", b =>
                {
                    b.Navigation("ReservedDates");
                });

            modelBuilder.Entity("HotelReserveAppServer.Models.User", b =>
                {
                    b.Navigation("Reserves");
                });
#pragma warning restore 612, 618
        }
    }
}
